# coding: utf-8

"""
    Tickcatcher API

    The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

    The version of the OpenAPI document: 1.1.5
    Contact: yagiz@iskirik.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tickcatcher.api.indicators_api import IndicatorsApi


class TestIndicatorsApi(unittest.TestCase):
    """IndicatorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IndicatorsApi()

    def tearDown(self) -> None:
        pass

    def test_adx(self) -> None:
        """Test case for adx

        Calculate Average Directional Index (ADX)
        """
        pass

    def test_atr(self) -> None:
        """Test case for atr

        Calculate Average True Range (ATR)
        """
        pass

    def test_bbands(self) -> None:
        """Test case for bbands

        Calculate Bollinger Bands
        """
        pass

    def test_cci(self) -> None:
        """Test case for cci

        Calculate Commodity Channel Index (CCI)
        """
        pass

    def test_ema(self) -> None:
        """Test case for ema

        Calculate Exponential Moving Average (EMA)
        """
        pass

    def test_heikenashi(self) -> None:
        """Test case for heikenashi

        Calculate Heiken Ashi
        """
        pass

    def test_ichimoku(self) -> None:
        """Test case for ichimoku

        Calculate Ichimoku Cloud
        """
        pass

    def test_keltner(self) -> None:
        """Test case for keltner

        Calculate Keltner Channels
        """
        pass

    def test_macd(self) -> None:
        """Test case for macd

        Calculate MACD
        """
        pass

    def test_pivot(self) -> None:
        """Test case for pivot

        Calculate Pivot Points
        """
        pass

    def test_psar(self) -> None:
        """Test case for psar

        Calculate Parabolic SAR
        """
        pass

    def test_rsi(self) -> None:
        """Test case for rsi

        Calculate Relative Strength Index (RSI)
        """
        pass

    def test_sma(self) -> None:
        """Test case for sma

        Calculate Simple Moving Average (SMA)
        """
        pass

    def test_stoch(self) -> None:
        """Test case for stoch

        Calculate Stochastic Oscillator
        """
        pass

    def test_supertrend(self) -> None:
        """Test case for supertrend

        Calculate SuperTrend
        """
        pass

    def test_volumema(self) -> None:
        """Test case for volumema

        Calculate Volume MA
        """
        pass

    def test_vwap(self) -> None:
        """Test case for vwap

        Calculate VWAP
        """
        pass

    def test_williamsr(self) -> None:
        """Test case for williamsr

        Calculate Williams %R
        """
        pass

    def test_zigzag(self) -> None:
        """Test case for zigzag

        Calculate ZigZag Indicator
        """
        pass


if __name__ == '__main__':
    unittest.main()
