# coding: utf-8

"""
    Tickcatcher API

    The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

    The version of the OpenAPI document: 1.1.0
    Contact: yagiz@iskirik.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tickcatcher.models.api_indicators_macd_post200_response_inner import ApiIndicatorsMacdPost200ResponseInner

class TestApiIndicatorsMacdPost200ResponseInner(unittest.TestCase):
    """ApiIndicatorsMacdPost200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiIndicatorsMacdPost200ResponseInner:
        """Test ApiIndicatorsMacdPost200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiIndicatorsMacdPost200ResponseInner`
        """
        model = ApiIndicatorsMacdPost200ResponseInner()
        if include_optional:
            return ApiIndicatorsMacdPost200ResponseInner(
                macd = 1.337,
                signal = 1.337,
                histogram = 1.337
            )
        else:
            return ApiIndicatorsMacdPost200ResponseInner(
        )
        """

    def testApiIndicatorsMacdPost200ResponseInner(self):
        """Test ApiIndicatorsMacdPost200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
