# coding: utf-8

"""
    Tickcatcher API

    The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

    The version of the OpenAPI document: 1.1.6
    Contact: yagiz@iskirik.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tickcatcher.models.heikenashi_request import HeikenashiRequest

class TestHeikenashiRequest(unittest.TestCase):
    """HeikenashiRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HeikenashiRequest:
        """Test HeikenashiRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HeikenashiRequest`
        """
        model = HeikenashiRequest()
        if include_optional:
            return HeikenashiRequest(
                data = [
                    tickcatcher.models.candle.Candle(
                        ts = '', 
                        open = 1.337, 
                        high = 1.337, 
                        low = 1.337, 
                        close = 1.337, 
                        volume = 1.337, )
                    ]
            )
        else:
            return HeikenashiRequest(
                data = [
                    tickcatcher.models.candle.Candle(
                        ts = '', 
                        open = 1.337, 
                        high = 1.337, 
                        low = 1.337, 
                        close = 1.337, 
                        volume = 1.337, )
                    ],
        )
        """

    def testHeikenashiRequest(self):
        """Test HeikenashiRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
