# coding: utf-8

"""
    Tickcatcher API

    The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

    The version of the OpenAPI document: 1.1.6
    Contact: yagiz@iskirik.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tickcatcher.api.calendar_api import CalendarApi


class TestCalendarApi(unittest.TestCase):
    """CalendarApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarApi()

    def tearDown(self) -> None:
        pass

    def test_calendar(self) -> None:
        """Test case for calendar

        Get economic calendar within a selected period
        """
        pass


if __name__ == '__main__':
    unittest.main()
