# coding: utf-8

"""
    Tickcatcher API

    The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

    The version of the OpenAPI document: 1.1.0
    Contact: yagiz@iskirik.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tickcatcher.api.pro_indicators_api import ProIndicatorsApi


class TestProIndicatorsApi(unittest.TestCase):
    """ProIndicatorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProIndicatorsApi()

    def tearDown(self) -> None:
        pass

    def test_api_indicators_bbands_post(self) -> None:
        """Test case for api_indicators_bbands_post

        Calculate Bollinger Bands
        """
        pass

    def test_api_indicators_macd_post(self) -> None:
        """Test case for api_indicators_macd_post

        Calculate MACD
        """
        pass

    def test_api_indicators_stoch_post(self) -> None:
        """Test case for api_indicators_stoch_post

        Calculate Stochastic Oscillator
        """
        pass

    def test_api_indicators_volumema_post(self) -> None:
        """Test case for api_indicators_volumema_post

        Calculate Volume MA
        """
        pass


if __name__ == '__main__':
    unittest.main()
