# coding: utf-8

"""
    Tickcatcher API

    The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.candle import Candle

class TestCandle(unittest.TestCase):
    """Candle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Candle:
        """Test Candle
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Candle`
        """
        model = Candle()
        if include_optional:
            return Candle(
                ts = 56,
                open = 1.337,
                high = 1.337,
                low = 1.337,
                close = 1.337,
                volume = 1.337
            )
        else:
            return Candle(
        )
        """

    def testCandle(self):
        """Test Candle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
