# coding: utf-8

"""
    Tickcatcher API

    The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.info import Info

class TestInfo(unittest.TestCase):
    """Info unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Info:
        """Test Info
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Info`
        """
        model = Info()
        if include_optional:
            return Info(
                package_name = 'Basic',
                usable_coins = [BTCUSDT, SOLUSDT, SUIUSDT],
                max_candles_on_request = 50000,
                usable_timeframes = [1m, 5m, 15m, 1h, 4h],
                custom_date_selection = True
            )
        else:
            return Info(
                package_name = 'Basic',
                usable_coins = [BTCUSDT, SOLUSDT, SUIUSDT],
                max_candles_on_request = 50000,
                usable_timeframes = [1m, 5m, 15m, 1h, 4h],
                custom_date_selection = True,
        )
        """

    def testInfo(self):
        """Test Info"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
