/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package tickcatcher.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param period The period for calculating SMA.
 */


data class ApiIndicatorsSmaPostRequestParams (

    /* The period for calculating SMA. */
    @Json(name = "period")
    val period: kotlin.Int? = 14

) {


}

