/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package tickcatcher.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param upper 
 * @param middle 
 * @param lower 
 */


data class ApiIndicatorsBbandsPost200ResponseInner (

    @Json(name = "upper")
    val upper: java.math.BigDecimal? = null,

    @Json(name = "middle")
    val middle: java.math.BigDecimal? = null,

    @Json(name = "lower")
    val lower: java.math.BigDecimal? = null

) {


}

