/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package tickcatcher.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param stochK 
 * @param stochD 
 */


data class Stoch200ResponseInner (

    @Json(name = "stochK")
    val stochK: java.math.BigDecimal? = null,

    @Json(name = "stochD")
    val stochD: java.math.BigDecimal? = null

) {


}

