/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package tickcatcher.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import tickcatcher.models.ApiIndicatorsBbandsPost200ResponseInner
import tickcatcher.models.HeikenashiRequest
import tickcatcher.models.KeltnerRequest
import tickcatcher.models.Pivot200ResponseInner

import com.squareup.moshi.Json

import tickcatcher.infrastructure.ApiClient
import tickcatcher.infrastructure.ApiResponse
import tickcatcher.infrastructure.ClientException
import tickcatcher.infrastructure.ClientError
import tickcatcher.infrastructure.ServerException
import tickcatcher.infrastructure.ServerError
import tickcatcher.infrastructure.MultiValueMap
import tickcatcher.infrastructure.PartConfig
import tickcatcher.infrastructure.RequestConfig
import tickcatcher.infrastructure.RequestMethod
import tickcatcher.infrastructure.ResponseType
import tickcatcher.infrastructure.Success
import tickcatcher.infrastructure.toMultiValue

class EnterpriseIndicatorsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://tickcatcher.p.rapidapi.com")
        }
    }

    /**
     * POST /api/indicators/keltner
     * Calculate Keltner Channels
     * 
     * @param keltnerRequest 
     * @return kotlin.collections.List<ApiIndicatorsBbandsPost200ResponseInner>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun keltner(keltnerRequest: KeltnerRequest) : kotlin.collections.List<ApiIndicatorsBbandsPost200ResponseInner> {
        val localVarResponse = keltnerWithHttpInfo(keltnerRequest = keltnerRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ApiIndicatorsBbandsPost200ResponseInner>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/indicators/keltner
     * Calculate Keltner Channels
     * 
     * @param keltnerRequest 
     * @return ApiResponse<kotlin.collections.List<ApiIndicatorsBbandsPost200ResponseInner>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun keltnerWithHttpInfo(keltnerRequest: KeltnerRequest) : ApiResponse<kotlin.collections.List<ApiIndicatorsBbandsPost200ResponseInner>?> {
        val localVariableConfig = keltnerRequestConfig(keltnerRequest = keltnerRequest)

        return request<KeltnerRequest, kotlin.collections.List<ApiIndicatorsBbandsPost200ResponseInner>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation keltner
     *
     * @param keltnerRequest 
     * @return RequestConfig
     */
    fun keltnerRequestConfig(keltnerRequest: KeltnerRequest) : RequestConfig<KeltnerRequest> {
        val localVariableBody = keltnerRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/indicators/keltner",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/indicators/pivot
     * Calculate Pivot Points
     * 
     * @param heikenashiRequest 
     * @return kotlin.collections.List<Pivot200ResponseInner>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun pivot(heikenashiRequest: HeikenashiRequest) : kotlin.collections.List<Pivot200ResponseInner> {
        val localVarResponse = pivotWithHttpInfo(heikenashiRequest = heikenashiRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<Pivot200ResponseInner>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/indicators/pivot
     * Calculate Pivot Points
     * 
     * @param heikenashiRequest 
     * @return ApiResponse<kotlin.collections.List<Pivot200ResponseInner>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun pivotWithHttpInfo(heikenashiRequest: HeikenashiRequest) : ApiResponse<kotlin.collections.List<Pivot200ResponseInner>?> {
        val localVariableConfig = pivotRequestConfig(heikenashiRequest = heikenashiRequest)

        return request<HeikenashiRequest, kotlin.collections.List<Pivot200ResponseInner>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation pivot
     *
     * @param heikenashiRequest 
     * @return RequestConfig
     */
    fun pivotRequestConfig(heikenashiRequest: HeikenashiRequest) : RequestConfig<HeikenashiRequest> {
        val localVariableBody = heikenashiRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/indicators/pivot",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/indicators/vwap
     * Calculate VWAP
     * 
     * @param heikenashiRequest 
     * @return kotlin.collections.List<java.math.BigDecimal>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun vwap(heikenashiRequest: HeikenashiRequest) : kotlin.collections.List<java.math.BigDecimal> {
        val localVarResponse = vwapWithHttpInfo(heikenashiRequest = heikenashiRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<java.math.BigDecimal>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/indicators/vwap
     * Calculate VWAP
     * 
     * @param heikenashiRequest 
     * @return ApiResponse<kotlin.collections.List<java.math.BigDecimal>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun vwapWithHttpInfo(heikenashiRequest: HeikenashiRequest) : ApiResponse<kotlin.collections.List<java.math.BigDecimal>?> {
        val localVariableConfig = vwapRequestConfig(heikenashiRequest = heikenashiRequest)

        return request<HeikenashiRequest, kotlin.collections.List<java.math.BigDecimal>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation vwap
     *
     * @param heikenashiRequest 
     * @return RequestConfig
     */
    fun vwapRequestConfig(heikenashiRequest: HeikenashiRequest) : RequestConfig<HeikenashiRequest> {
        val localVariableBody = heikenashiRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/indicators/vwap",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/indicators/zigzag
     * Calculate ZigZag Indicator
     * 
     * @param heikenashiRequest 
     * @return kotlin.collections.List<java.math.BigDecimal?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun zigzag(heikenashiRequest: HeikenashiRequest) : kotlin.collections.List<java.math.BigDecimal?> {
        val localVarResponse = zigzagWithHttpInfo(heikenashiRequest = heikenashiRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<java.math.BigDecimal?>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/indicators/zigzag
     * Calculate ZigZag Indicator
     * 
     * @param heikenashiRequest 
     * @return ApiResponse<kotlin.collections.List<java.math.BigDecimal?>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun zigzagWithHttpInfo(heikenashiRequest: HeikenashiRequest) : ApiResponse<kotlin.collections.List<java.math.BigDecimal?>?> {
        val localVariableConfig = zigzagRequestConfig(heikenashiRequest = heikenashiRequest)

        return request<HeikenashiRequest, kotlin.collections.List<java.math.BigDecimal?>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation zigzag
     *
     * @param heikenashiRequest 
     * @return RequestConfig
     */
    fun zigzagRequestConfig(heikenashiRequest: HeikenashiRequest) : RequestConfig<HeikenashiRequest> {
        val localVariableBody = heikenashiRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/indicators/zigzag",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
