/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package tickcatcher.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import tickcatcher.models.Adx200ResponseInner
import tickcatcher.models.EmaRequest
import tickcatcher.models.PsarRequest

import com.squareup.moshi.Json

import tickcatcher.infrastructure.ApiClient
import tickcatcher.infrastructure.ApiResponse
import tickcatcher.infrastructure.ClientException
import tickcatcher.infrastructure.ClientError
import tickcatcher.infrastructure.ServerException
import tickcatcher.infrastructure.ServerError
import tickcatcher.infrastructure.MultiValueMap
import tickcatcher.infrastructure.PartConfig
import tickcatcher.infrastructure.RequestConfig
import tickcatcher.infrastructure.RequestMethod
import tickcatcher.infrastructure.ResponseType
import tickcatcher.infrastructure.Success
import tickcatcher.infrastructure.toMultiValue

class UltraIndicatorsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://tickcatcher.p.rapidapi.com")
        }
    }

    /**
     * POST /api/indicators/adx
     * Calculate Average Directional Index (ADX)
     * 
     * @param emaRequest 
     * @return kotlin.collections.List<Adx200ResponseInner>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adx(emaRequest: EmaRequest) : kotlin.collections.List<Adx200ResponseInner> {
        val localVarResponse = adxWithHttpInfo(emaRequest = emaRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<Adx200ResponseInner>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/indicators/adx
     * Calculate Average Directional Index (ADX)
     * 
     * @param emaRequest 
     * @return ApiResponse<kotlin.collections.List<Adx200ResponseInner>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adxWithHttpInfo(emaRequest: EmaRequest) : ApiResponse<kotlin.collections.List<Adx200ResponseInner>?> {
        val localVariableConfig = adxRequestConfig(emaRequest = emaRequest)

        return request<EmaRequest, kotlin.collections.List<Adx200ResponseInner>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adx
     *
     * @param emaRequest 
     * @return RequestConfig
     */
    fun adxRequestConfig(emaRequest: EmaRequest) : RequestConfig<EmaRequest> {
        val localVariableBody = emaRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/indicators/adx",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/indicators/atr
     * Calculate Average True Range (ATR)
     * 
     * @param emaRequest 
     * @return kotlin.collections.List<java.math.BigDecimal>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun atr(emaRequest: EmaRequest) : kotlin.collections.List<java.math.BigDecimal> {
        val localVarResponse = atrWithHttpInfo(emaRequest = emaRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<java.math.BigDecimal>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/indicators/atr
     * Calculate Average True Range (ATR)
     * 
     * @param emaRequest 
     * @return ApiResponse<kotlin.collections.List<java.math.BigDecimal>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun atrWithHttpInfo(emaRequest: EmaRequest) : ApiResponse<kotlin.collections.List<java.math.BigDecimal>?> {
        val localVariableConfig = atrRequestConfig(emaRequest = emaRequest)

        return request<EmaRequest, kotlin.collections.List<java.math.BigDecimal>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation atr
     *
     * @param emaRequest 
     * @return RequestConfig
     */
    fun atrRequestConfig(emaRequest: EmaRequest) : RequestConfig<EmaRequest> {
        val localVariableBody = emaRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/indicators/atr",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/indicators/cci
     * Calculate Commodity Channel Index (CCI)
     * 
     * @param emaRequest 
     * @return kotlin.collections.List<java.math.BigDecimal>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun cci(emaRequest: EmaRequest) : kotlin.collections.List<java.math.BigDecimal> {
        val localVarResponse = cciWithHttpInfo(emaRequest = emaRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<java.math.BigDecimal>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/indicators/cci
     * Calculate Commodity Channel Index (CCI)
     * 
     * @param emaRequest 
     * @return ApiResponse<kotlin.collections.List<java.math.BigDecimal>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun cciWithHttpInfo(emaRequest: EmaRequest) : ApiResponse<kotlin.collections.List<java.math.BigDecimal>?> {
        val localVariableConfig = cciRequestConfig(emaRequest = emaRequest)

        return request<EmaRequest, kotlin.collections.List<java.math.BigDecimal>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation cci
     *
     * @param emaRequest 
     * @return RequestConfig
     */
    fun cciRequestConfig(emaRequest: EmaRequest) : RequestConfig<EmaRequest> {
        val localVariableBody = emaRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/indicators/cci",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/indicators/psar
     * Calculate Parabolic SAR
     * 
     * @param psarRequest 
     * @return kotlin.collections.List<java.math.BigDecimal>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun psar(psarRequest: PsarRequest) : kotlin.collections.List<java.math.BigDecimal> {
        val localVarResponse = psarWithHttpInfo(psarRequest = psarRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<java.math.BigDecimal>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/indicators/psar
     * Calculate Parabolic SAR
     * 
     * @param psarRequest 
     * @return ApiResponse<kotlin.collections.List<java.math.BigDecimal>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun psarWithHttpInfo(psarRequest: PsarRequest) : ApiResponse<kotlin.collections.List<java.math.BigDecimal>?> {
        val localVariableConfig = psarRequestConfig(psarRequest = psarRequest)

        return request<PsarRequest, kotlin.collections.List<java.math.BigDecimal>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation psar
     *
     * @param psarRequest 
     * @return RequestConfig
     */
    fun psarRequestConfig(psarRequest: PsarRequest) : RequestConfig<PsarRequest> {
        val localVariableBody = psarRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/indicators/psar",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
