// <auto-generated>
/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yagiz@iskirik.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using tickcatcher.Client;

namespace tickcatcher.Model
{
    /// <summary>
    /// ApiIndicatorsSmaPostRequestParams
    /// </summary>
    public partial class ApiIndicatorsSmaPostRequestParams : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiIndicatorsSmaPostRequestParams" /> class.
        /// </summary>
        /// <param name="period">The period for calculating SMA. (default to 14)</param>
        [JsonConstructor]
        public ApiIndicatorsSmaPostRequestParams(Option<int?> period = default)
        {
            PeriodOption = period;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Period
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PeriodOption { get; private set; }

        /// <summary>
        /// The period for calculating SMA.
        /// </summary>
        /// <value>The period for calculating SMA.</value>
        [JsonPropertyName("period")]
        public int? Period { get { return this.PeriodOption; } set { this.PeriodOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiIndicatorsSmaPostRequestParams {\n");
            sb.Append("  Period: ").Append(Period).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiIndicatorsSmaPostRequestParams" />
    /// </summary>
    public class ApiIndicatorsSmaPostRequestParamsJsonConverter : JsonConverter<ApiIndicatorsSmaPostRequestParams>
    {
        /// <summary>
        /// Deserializes json to <see cref="ApiIndicatorsSmaPostRequestParams" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiIndicatorsSmaPostRequestParams Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> period = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "period":
                            period = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (period.IsSet && period.Value == null)
                throw new ArgumentNullException(nameof(period), "Property is not nullable for class ApiIndicatorsSmaPostRequestParams.");

            return new ApiIndicatorsSmaPostRequestParams(period);
        }

        /// <summary>
        /// Serializes a <see cref="ApiIndicatorsSmaPostRequestParams" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiIndicatorsSmaPostRequestParams"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiIndicatorsSmaPostRequestParams apiIndicatorsSmaPostRequestParams, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiIndicatorsSmaPostRequestParams, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiIndicatorsSmaPostRequestParams" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiIndicatorsSmaPostRequestParams"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiIndicatorsSmaPostRequestParams apiIndicatorsSmaPostRequestParams, JsonSerializerOptions jsonSerializerOptions)
        {
            if (apiIndicatorsSmaPostRequestParams.PeriodOption.IsSet)
                writer.WriteNumber("period", apiIndicatorsSmaPostRequestParams.PeriodOption.Value!.Value);
        }
    }
}
