// <auto-generated>
/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yagiz@iskirik.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using tickcatcher.Client;

namespace tickcatcher.Model
{
    /// <summary>
    /// Heikenashi200Response
    /// </summary>
    public partial class Heikenashi200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Heikenashi200Response" /> class.
        /// </summary>
        /// <param name="open">open</param>
        /// <param name="high">high</param>
        /// <param name="low">low</param>
        /// <param name="close">close</param>
        [JsonConstructor]
        public Heikenashi200Response(Option<List<decimal>?> open = default, Option<List<decimal>?> high = default, Option<List<decimal>?> low = default, Option<List<decimal>?> close = default)
        {
            OpenOption = open;
            HighOption = high;
            LowOption = low;
            CloseOption = close;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Open
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<decimal>?> OpenOption { get; private set; }

        /// <summary>
        /// Gets or Sets Open
        /// </summary>
        [JsonPropertyName("open")]
        public List<decimal>? Open { get { return this.OpenOption; } set { this.OpenOption = new(value); } }

        /// <summary>
        /// Used to track the state of High
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<decimal>?> HighOption { get; private set; }

        /// <summary>
        /// Gets or Sets High
        /// </summary>
        [JsonPropertyName("high")]
        public List<decimal>? High { get { return this.HighOption; } set { this.HighOption = new(value); } }

        /// <summary>
        /// Used to track the state of Low
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<decimal>?> LowOption { get; private set; }

        /// <summary>
        /// Gets or Sets Low
        /// </summary>
        [JsonPropertyName("low")]
        public List<decimal>? Low { get { return this.LowOption; } set { this.LowOption = new(value); } }

        /// <summary>
        /// Used to track the state of Close
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<decimal>?> CloseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Close
        /// </summary>
        [JsonPropertyName("close")]
        public List<decimal>? Close { get { return this.CloseOption; } set { this.CloseOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Heikenashi200Response {\n");
            sb.Append("  Open: ").Append(Open).Append("\n");
            sb.Append("  High: ").Append(High).Append("\n");
            sb.Append("  Low: ").Append(Low).Append("\n");
            sb.Append("  Close: ").Append(Close).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Heikenashi200Response" />
    /// </summary>
    public class Heikenashi200ResponseJsonConverter : JsonConverter<Heikenashi200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="Heikenashi200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Heikenashi200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<decimal>?> open = default;
            Option<List<decimal>?> high = default;
            Option<List<decimal>?> low = default;
            Option<List<decimal>?> close = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "open":
                            open = new Option<List<decimal>?>(JsonSerializer.Deserialize<List<decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "high":
                            high = new Option<List<decimal>?>(JsonSerializer.Deserialize<List<decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "low":
                            low = new Option<List<decimal>?>(JsonSerializer.Deserialize<List<decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "close":
                            close = new Option<List<decimal>?>(JsonSerializer.Deserialize<List<decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (open.IsSet && open.Value == null)
                throw new ArgumentNullException(nameof(open), "Property is not nullable for class Heikenashi200Response.");

            if (high.IsSet && high.Value == null)
                throw new ArgumentNullException(nameof(high), "Property is not nullable for class Heikenashi200Response.");

            if (low.IsSet && low.Value == null)
                throw new ArgumentNullException(nameof(low), "Property is not nullable for class Heikenashi200Response.");

            if (close.IsSet && close.Value == null)
                throw new ArgumentNullException(nameof(close), "Property is not nullable for class Heikenashi200Response.");

            return new Heikenashi200Response(open, high, low, close);
        }

        /// <summary>
        /// Serializes a <see cref="Heikenashi200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="heikenashi200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Heikenashi200Response heikenashi200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, heikenashi200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Heikenashi200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="heikenashi200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Heikenashi200Response heikenashi200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (heikenashi200Response.OpenOption.IsSet && heikenashi200Response.Open == null)
                throw new ArgumentNullException(nameof(heikenashi200Response.Open), "Property is required for class Heikenashi200Response.");

            if (heikenashi200Response.HighOption.IsSet && heikenashi200Response.High == null)
                throw new ArgumentNullException(nameof(heikenashi200Response.High), "Property is required for class Heikenashi200Response.");

            if (heikenashi200Response.LowOption.IsSet && heikenashi200Response.Low == null)
                throw new ArgumentNullException(nameof(heikenashi200Response.Low), "Property is required for class Heikenashi200Response.");

            if (heikenashi200Response.CloseOption.IsSet && heikenashi200Response.Close == null)
                throw new ArgumentNullException(nameof(heikenashi200Response.Close), "Property is required for class Heikenashi200Response.");

            if (heikenashi200Response.OpenOption.IsSet)
            {
                writer.WritePropertyName("open");
                JsonSerializer.Serialize(writer, heikenashi200Response.Open, jsonSerializerOptions);
            }
            if (heikenashi200Response.HighOption.IsSet)
            {
                writer.WritePropertyName("high");
                JsonSerializer.Serialize(writer, heikenashi200Response.High, jsonSerializerOptions);
            }
            if (heikenashi200Response.LowOption.IsSet)
            {
                writer.WritePropertyName("low");
                JsonSerializer.Serialize(writer, heikenashi200Response.Low, jsonSerializerOptions);
            }
            if (heikenashi200Response.CloseOption.IsSet)
            {
                writer.WritePropertyName("close");
                JsonSerializer.Serialize(writer, heikenashi200Response.Close, jsonSerializerOptions);
            }
        }
    }
}
