// <auto-generated>
/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yagiz@iskirik.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using tickcatcher.Client;

namespace tickcatcher.Model
{
    /// <summary>
    /// SupertrendRequest
    /// </summary>
    public partial class SupertrendRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SupertrendRequest" /> class.
        /// </summary>
        /// <param name="data">data</param>
        /// <param name="params">params</param>
        [JsonConstructor]
        public SupertrendRequest(CandleData data, Option<SupertrendRequestParams?> @params = default)
        {
            Data = data;
            ParamsOption = @params;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public CandleData Data { get; set; }

        /// <summary>
        /// Used to track the state of Params
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SupertrendRequestParams?> ParamsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Params
        /// </summary>
        [JsonPropertyName("params")]
        public SupertrendRequestParams? Params { get { return this.ParamsOption; } set { this.ParamsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SupertrendRequest {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Params: ").Append(Params).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SupertrendRequest" />
    /// </summary>
    public class SupertrendRequestJsonConverter : JsonConverter<SupertrendRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SupertrendRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SupertrendRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CandleData?> data = default;
            Option<SupertrendRequestParams?> varParams = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "data":
                            data = new Option<CandleData?>(JsonSerializer.Deserialize<CandleData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "params":
                            varParams = new Option<SupertrendRequestParams?>(JsonSerializer.Deserialize<SupertrendRequestParams>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!data.IsSet)
                throw new ArgumentException("Property is required for class SupertrendRequest.", nameof(data));

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class SupertrendRequest.");

            if (varParams.IsSet && varParams.Value == null)
                throw new ArgumentNullException(nameof(varParams), "Property is not nullable for class SupertrendRequest.");

            return new SupertrendRequest(data.Value!, varParams);
        }

        /// <summary>
        /// Serializes a <see cref="SupertrendRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="supertrendRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SupertrendRequest supertrendRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, supertrendRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SupertrendRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="supertrendRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SupertrendRequest supertrendRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (supertrendRequest.Data == null)
                throw new ArgumentNullException(nameof(supertrendRequest.Data), "Property is required for class SupertrendRequest.");

            if (supertrendRequest.ParamsOption.IsSet && supertrendRequest.Params == null)
                throw new ArgumentNullException(nameof(supertrendRequest.Params), "Property is required for class SupertrendRequest.");

            writer.WritePropertyName("data");
            JsonSerializer.Serialize(writer, supertrendRequest.Data, jsonSerializerOptions);
            if (supertrendRequest.ParamsOption.IsSet)
            {
                writer.WritePropertyName("params");
                JsonSerializer.Serialize(writer, supertrendRequest.Params, jsonSerializerOptions);
            }
        }
    }
}
