/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yagiz@iskirik.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using tickcatcher.Api;
using tickcatcher.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace tickcatcher.Test.Api
{
    /// <summary>
    ///  Class for testing BasicIndicatorsApi
    /// </summary>
    public sealed class BasicIndicatorsApiTests : ApiTestsBase
    {
        private readonly IBasicIndicatorsApi _instance;

        public BasicIndicatorsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IBasicIndicatorsApi>();
        }

        /// <summary>
        /// Test ApiIndicatorsEmaPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiIndicatorsEmaPostAsyncTest()
        {
            ApiIndicatorsEmaPostRequest apiIndicatorsEmaPostRequest = default!;
            var response = await _instance.ApiIndicatorsEmaPostAsync(apiIndicatorsEmaPostRequest);
            var model = response.Ok();
            Assert.IsType<List<decimal>>(model);
        }

        /// <summary>
        /// Test ApiIndicatorsRsiPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiIndicatorsRsiPostAsyncTest()
        {
            ApiIndicatorsEmaPostRequest apiIndicatorsEmaPostRequest = default!;
            var response = await _instance.ApiIndicatorsRsiPostAsync(apiIndicatorsEmaPostRequest);
            var model = response.Ok();
            Assert.IsType<List<decimal>>(model);
        }

        /// <summary>
        /// Test ApiIndicatorsSmaPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiIndicatorsSmaPostAsyncTest()
        {
            ApiIndicatorsSmaPostRequest apiIndicatorsSmaPostRequest = default!;
            var response = await _instance.ApiIndicatorsSmaPostAsync(apiIndicatorsSmaPostRequest);
            var model = response.Ok();
            Assert.IsType<List<decimal>>(model);
        }
    }
}
