/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: yagiz@iskirik.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Security.Cryptography;
using tickcatcher.Client;
using tickcatcher.Api;
using tickcatcher.Extensions;
using Xunit;

namespace tickcatcher.Test.Api
{
    /// <summary>
    ///  Tests the dependency injection.
    /// </summary>
    public class DependencyInjectionTest
    {
        private readonly IHost _hostUsingConfigureWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {
                ApiKeyToken apiKeyToken1 = new("<token>", ClientUtils.ApiKeyHeader.X_RapidAPI_Key, timeout: TimeSpan.FromSeconds(1));
                options.AddTokens(apiKeyToken1);
            })
            .Build();

        private readonly IHost _hostUsingConfigureWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {
                ApiKeyToken apiKeyToken1 = new("<token>", ClientUtils.ApiKeyHeader.X_RapidAPI_Key, timeout: TimeSpan.FromSeconds(1));
                options.AddTokens(apiKeyToken1);
                options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
            })
            .Build();

        private readonly IHost _hostUsingAddWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {
                    ApiKeyToken apiKeyToken1 = new("<token>", ClientUtils.ApiKeyHeader.X_RapidAPI_Key, timeout: TimeSpan.FromSeconds(1));
                    options.AddTokens(apiKeyToken1);
                });
            })
            .Build();

        private readonly IHost _hostUsingAddWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {
                    ApiKeyToken apiKeyToken1 = new("<token>", ClientUtils.ApiKeyHeader.X_RapidAPI_Key, timeout: TimeSpan.FromSeconds(1));
                    options.AddTokens(apiKeyToken1);
                    options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
                });
            })
            .Build();

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithAClientTest()
        {
            var calendarApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<ICalendarApi>();
            Assert.True(calendarApi.HttpClient.BaseAddress != null);

            var candlesApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<ICandlesApi>();
            Assert.True(candlesApi.HttpClient.BaseAddress != null);

            var generalApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IGeneralApi>();
            Assert.True(generalApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithoutAClientTest()
        {
            var calendarApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<ICalendarApi>();
            Assert.True(calendarApi.HttpClient.BaseAddress != null);

            var candlesApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<ICandlesApi>();
            Assert.True(candlesApi.HttpClient.BaseAddress != null);

            var generalApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IGeneralApi>();
            Assert.True(generalApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithAClientTest()
        {
            var calendarApi = _hostUsingAddWithAClient.Services.GetRequiredService<ICalendarApi>();
            Assert.True(calendarApi.HttpClient.BaseAddress != null);
            
            var candlesApi = _hostUsingAddWithAClient.Services.GetRequiredService<ICandlesApi>();
            Assert.True(candlesApi.HttpClient.BaseAddress != null);
            
            var generalApi = _hostUsingAddWithAClient.Services.GetRequiredService<IGeneralApi>();
            Assert.True(generalApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithoutAClientTest()
        {
            var calendarApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<ICalendarApi>();
            Assert.True(calendarApi.HttpClient.BaseAddress != null);

            var candlesApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<ICandlesApi>();
            Assert.True(candlesApi.HttpClient.BaseAddress != null);

            var generalApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IGeneralApi>();
            Assert.True(generalApi.HttpClient.BaseAddress != null);
        }
    }
}
