/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yagiz@iskirik.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using tickcatcher.Model;
using tickcatcher.Client;
using System.Reflection;

namespace tickcatcher.Test.Model
{
    /// <summary>
    ///  Class for testing ApiIndicatorsMacdPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiIndicatorsMacdPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiIndicatorsMacdPostRequest
        //private ApiIndicatorsMacdPostRequest instance;

        public ApiIndicatorsMacdPostRequestTests()
        {
            // TODO uncomment below to create an instance of ApiIndicatorsMacdPostRequest
            //instance = new ApiIndicatorsMacdPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiIndicatorsMacdPostRequest
        /// </summary>
        [Fact]
        public void ApiIndicatorsMacdPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiIndicatorsMacdPostRequest
            //Assert.IsType<ApiIndicatorsMacdPostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }
    }
}
