/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yagiz@iskirik.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using tickcatcher.Model;
using tickcatcher.Client;
using System.Reflection;

namespace tickcatcher.Test.Model
{
    /// <summary>
    ///  Class for testing ApiIndicatorsEmaPostRequestParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiIndicatorsEmaPostRequestParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiIndicatorsEmaPostRequestParams
        //private ApiIndicatorsEmaPostRequestParams instance;

        public ApiIndicatorsEmaPostRequestParamsTests()
        {
            // TODO uncomment below to create an instance of ApiIndicatorsEmaPostRequestParams
            //instance = new ApiIndicatorsEmaPostRequestParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiIndicatorsEmaPostRequestParams
        /// </summary>
        [Fact]
        public void ApiIndicatorsEmaPostRequestParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiIndicatorsEmaPostRequestParams
            //Assert.IsType<ApiIndicatorsEmaPostRequestParams>(instance);
        }

        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
    }
}
