/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: yagiz@iskirik.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using tickcatcher.Model;
using tickcatcher.Client;
using System.Reflection;

namespace tickcatcher.Test.Model
{
    /// <summary>
    ///  Class for testing EmaRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmaRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmaRequest
        //private EmaRequest instance;

        public EmaRequestTests()
        {
            // TODO uncomment below to create an instance of EmaRequest
            //instance = new EmaRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmaRequest
        /// </summary>
        [Fact]
        public void EmaRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmaRequest
            //Assert.IsType<EmaRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }
    }
}
