/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: yagiz@iskirik.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using tickcatcher.Model;
using tickcatcher.Client;
using System.Reflection;

namespace tickcatcher.Test.Model
{
    /// <summary>
    ///  Class for testing StochRequestParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StochRequestParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StochRequestParams
        //private StochRequestParams instance;

        public StochRequestParamsTests()
        {
            // TODO uncomment below to create an instance of StochRequestParams
            //instance = new StochRequestParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StochRequestParams
        /// </summary>
        [Fact]
        public void StochRequestParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" StochRequestParams
            //Assert.IsType<StochRequestParams>(instance);
        }

        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }

        /// <summary>
        /// Test the property 'SignalPeriod'
        /// </summary>
        [Fact]
        public void SignalPeriodTest()
        {
            // TODO unit test for the property 'SignalPeriod'
        }
    }
}
