/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.5
 * Contact: yagiz@iskirik.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using tickcatcher.Model;
using tickcatcher.Client;
using System.Reflection;

namespace tickcatcher.Test.Model
{
    /// <summary>
    ///  Class for testing VwapRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VwapRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VwapRequest
        //private VwapRequest instance;

        public VwapRequestTests()
        {
            // TODO uncomment below to create an instance of VwapRequest
            //instance = new VwapRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VwapRequest
        /// </summary>
        [Fact]
        public void VwapRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" VwapRequest
            //Assert.IsType<VwapRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
