/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package tickcatcher.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import tickcatcher.models.ApiIndicatorsSmaPostRequestParams

class ApiIndicatorsSmaPostRequestParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiIndicatorsSmaPostRequestParams
        //val modelInstance = ApiIndicatorsSmaPostRequestParams()

        // to test the property `period` - The period for calculating SMA.
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

    }
}
