/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package tickcatcher.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import tickcatcher.models.AtrRequest
import tickcatcher.models.Candle
import tickcatcher.models.EmaRequestParams

class AtrRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AtrRequest
        //val modelInstance = AtrRequest()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `params`
        should("test params") {
            // uncomment below to test the property
            //modelInstance.params shouldBe ("TODO")
        }

    }
}
