/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package tickcatcher.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import tickcatcher.models.BbandsRequestParams

class BbandsRequestParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BbandsRequestParams
        //val modelInstance = BbandsRequestParams()

        // to test the property `period`
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

        // to test the property `stdDev`
        should("test stdDev") {
            // uncomment below to test the property
            //modelInstance.stdDev shouldBe ("TODO")
        }

    }
}
