/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package tickcatcher.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import tickcatcher.models.CandleData

class CandleDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CandleData
        //val modelInstance = CandleData()

        // to test the property `close`
        should("test close") {
            // uncomment below to test the property
            //modelInstance.close shouldBe ("TODO")
        }

        // to test the property ``open``
        should("test `open`") {
            // uncomment below to test the property
            //modelInstance.`open` shouldBe ("TODO")
        }

        // to test the property `high`
        should("test high") {
            // uncomment below to test the property
            //modelInstance.high shouldBe ("TODO")
        }

        // to test the property `low`
        should("test low") {
            // uncomment below to test the property
            //modelInstance.low shouldBe ("TODO")
        }

        // to test the property `volume`
        should("test volume") {
            // uncomment below to test the property
            //modelInstance.volume shouldBe ("TODO")
        }

    }
}
