/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package tickcatcher.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import tickcatcher.models.IchimokuRequestParams

class IchimokuRequestParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IchimokuRequestParams
        //val modelInstance = IchimokuRequestParams()

        // to test the property `conversionPeriod`
        should("test conversionPeriod") {
            // uncomment below to test the property
            //modelInstance.conversionPeriod shouldBe ("TODO")
        }

        // to test the property `basePeriod`
        should("test basePeriod") {
            // uncomment below to test the property
            //modelInstance.basePeriod shouldBe ("TODO")
        }

        // to test the property `spanPeriod`
        should("test spanPeriod") {
            // uncomment below to test the property
            //modelInstance.spanPeriod shouldBe ("TODO")
        }

        // to test the property `displacement`
        should("test displacement") {
            // uncomment below to test the property
            //modelInstance.displacement shouldBe ("TODO")
        }

    }
}
