/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiIndicatorsBbandsPost200ResponseInner
 */
export interface ApiIndicatorsBbandsPost200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof ApiIndicatorsBbandsPost200ResponseInner
     */
    upper?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiIndicatorsBbandsPost200ResponseInner
     */
    middle?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiIndicatorsBbandsPost200ResponseInner
     */
    lower?: number;
}

/**
 * Check if a given object implements the ApiIndicatorsBbandsPost200ResponseInner interface.
 */
export function instanceOfApiIndicatorsBbandsPost200ResponseInner(value: object): value is ApiIndicatorsBbandsPost200ResponseInner {
    return true;
}

export function ApiIndicatorsBbandsPost200ResponseInnerFromJSON(json: any): ApiIndicatorsBbandsPost200ResponseInner {
    return ApiIndicatorsBbandsPost200ResponseInnerFromJSONTyped(json, false);
}

export function ApiIndicatorsBbandsPost200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiIndicatorsBbandsPost200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'upper': json['upper'] == null ? undefined : json['upper'],
        'middle': json['middle'] == null ? undefined : json['middle'],
        'lower': json['lower'] == null ? undefined : json['lower'],
    };
}

export function ApiIndicatorsBbandsPost200ResponseInnerToJSON(json: any): ApiIndicatorsBbandsPost200ResponseInner {
    return ApiIndicatorsBbandsPost200ResponseInnerToJSONTyped(json, false);
}

export function ApiIndicatorsBbandsPost200ResponseInnerToJSONTyped(value?: ApiIndicatorsBbandsPost200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'upper': value['upper'],
        'middle': value['middle'],
        'lower': value['lower'],
    };
}

