/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiIndicatorsBbandsPostRequestParams
 */
export interface ApiIndicatorsBbandsPostRequestParams {
    /**
     * 
     * @type {number}
     * @memberof ApiIndicatorsBbandsPostRequestParams
     */
    period?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiIndicatorsBbandsPostRequestParams
     */
    stdDev?: number;
}

/**
 * Check if a given object implements the ApiIndicatorsBbandsPostRequestParams interface.
 */
export function instanceOfApiIndicatorsBbandsPostRequestParams(value: object): value is ApiIndicatorsBbandsPostRequestParams {
    return true;
}

export function ApiIndicatorsBbandsPostRequestParamsFromJSON(json: any): ApiIndicatorsBbandsPostRequestParams {
    return ApiIndicatorsBbandsPostRequestParamsFromJSONTyped(json, false);
}

export function ApiIndicatorsBbandsPostRequestParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiIndicatorsBbandsPostRequestParams {
    if (json == null) {
        return json;
    }
    return {
        
        'period': json['period'] == null ? undefined : json['period'],
        'stdDev': json['stdDev'] == null ? undefined : json['stdDev'],
    };
}

export function ApiIndicatorsBbandsPostRequestParamsToJSON(json: any): ApiIndicatorsBbandsPostRequestParams {
    return ApiIndicatorsBbandsPostRequestParamsToJSONTyped(json, false);
}

export function ApiIndicatorsBbandsPostRequestParamsToJSONTyped(value?: ApiIndicatorsBbandsPostRequestParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': value['period'],
        'stdDev': value['stdDev'],
    };
}

