/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CandleData } from './CandleData';
import {
    CandleDataFromJSON,
    CandleDataFromJSONTyped,
    CandleDataToJSON,
    CandleDataToJSONTyped,
} from './CandleData';
import type { ApiIndicatorsSmaPostRequestParams } from './ApiIndicatorsSmaPostRequestParams';
import {
    ApiIndicatorsSmaPostRequestParamsFromJSON,
    ApiIndicatorsSmaPostRequestParamsFromJSONTyped,
    ApiIndicatorsSmaPostRequestParamsToJSON,
    ApiIndicatorsSmaPostRequestParamsToJSONTyped,
} from './ApiIndicatorsSmaPostRequestParams';

/**
 * 
 * @export
 * @interface ApiIndicatorsSmaPostRequest
 */
export interface ApiIndicatorsSmaPostRequest {
    /**
     * 
     * @type {CandleData}
     * @memberof ApiIndicatorsSmaPostRequest
     */
    data: CandleData;
    /**
     * 
     * @type {ApiIndicatorsSmaPostRequestParams}
     * @memberof ApiIndicatorsSmaPostRequest
     */
    params?: ApiIndicatorsSmaPostRequestParams;
}

/**
 * Check if a given object implements the ApiIndicatorsSmaPostRequest interface.
 */
export function instanceOfApiIndicatorsSmaPostRequest(value: object): value is ApiIndicatorsSmaPostRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ApiIndicatorsSmaPostRequestFromJSON(json: any): ApiIndicatorsSmaPostRequest {
    return ApiIndicatorsSmaPostRequestFromJSONTyped(json, false);
}

export function ApiIndicatorsSmaPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiIndicatorsSmaPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CandleDataFromJSON(json['data']),
        'params': json['params'] == null ? undefined : ApiIndicatorsSmaPostRequestParamsFromJSON(json['params']),
    };
}

export function ApiIndicatorsSmaPostRequestToJSON(json: any): ApiIndicatorsSmaPostRequest {
    return ApiIndicatorsSmaPostRequestToJSONTyped(json, false);
}

export function ApiIndicatorsSmaPostRequestToJSONTyped(value?: ApiIndicatorsSmaPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CandleDataToJSON(value['data']),
        'params': ApiIndicatorsSmaPostRequestParamsToJSON(value['params']),
    };
}

