/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key or TickCatcher Direct Key. 
 *
 * The version of the OpenAPI document: 1.1.7
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Candle } from './Candle';
import {
    CandleFromJSON,
    CandleFromJSONTyped,
    CandleToJSON,
    CandleToJSONTyped,
} from './Candle';
import type { EmaRequestParams } from './EmaRequestParams';
import {
    EmaRequestParamsFromJSON,
    EmaRequestParamsFromJSONTyped,
    EmaRequestParamsToJSON,
    EmaRequestParamsToJSONTyped,
} from './EmaRequestParams';

/**
 * 
 * @export
 * @interface AtrRequest
 */
export interface AtrRequest {
    /**
     * 
     * @type {Array<Candle>}
     * @memberof AtrRequest
     */
    data: Array<Candle>;
    /**
     * 
     * @type {EmaRequestParams}
     * @memberof AtrRequest
     */
    params?: EmaRequestParams;
}

/**
 * Check if a given object implements the AtrRequest interface.
 */
export function instanceOfAtrRequest(value: object): value is AtrRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AtrRequestFromJSON(json: any): AtrRequest {
    return AtrRequestFromJSONTyped(json, false);
}

export function AtrRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AtrRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CandleFromJSON)),
        'params': json['params'] == null ? undefined : EmaRequestParamsFromJSON(json['params']),
    };
}

export function AtrRequestToJSON(json: any): AtrRequest {
    return AtrRequestToJSONTyped(json, false);
}

export function AtrRequestToJSONTyped(value?: AtrRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CandleToJSON)),
        'params': EmaRequestParamsToJSON(value['params']),
    };
}

