/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key or TickCatcher Direct Key. 
 *
 * The version of the OpenAPI document: 1.1.7
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Candle
 */
export interface Candle {
    /**
     * Unix timestamp in milliseconds
     * @type {string}
     * @memberof Candle
     */
    ts?: string;
    /**
     * Opening price
     * @type {number}
     * @memberof Candle
     */
    open?: number;
    /**
     * Highest price
     * @type {number}
     * @memberof Candle
     */
    high?: number;
    /**
     * Lowest price
     * @type {number}
     * @memberof Candle
     */
    low?: number;
    /**
     * Closing price
     * @type {number}
     * @memberof Candle
     */
    close?: number;
    /**
     * Volume traded
     * @type {number}
     * @memberof Candle
     */
    volume?: number;
}

/**
 * Check if a given object implements the Candle interface.
 */
export function instanceOfCandle(value: object): value is Candle {
    return true;
}

export function CandleFromJSON(json: any): Candle {
    return CandleFromJSONTyped(json, false);
}

export function CandleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Candle {
    if (json == null) {
        return json;
    }
    return {
        
        'ts': json['ts'] == null ? undefined : json['ts'],
        'open': json['open'] == null ? undefined : json['open'],
        'high': json['high'] == null ? undefined : json['high'],
        'low': json['low'] == null ? undefined : json['low'],
        'close': json['close'] == null ? undefined : json['close'],
        'volume': json['volume'] == null ? undefined : json['volume'],
    };
}

export function CandleToJSON(json: any): Candle {
    return CandleToJSONTyped(json, false);
}

export function CandleToJSONTyped(value?: Candle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ts': value['ts'],
        'open': value['open'],
        'high': value['high'],
        'low': value['low'],
        'close': value['close'],
        'volume': value['volume'],
    };
}

