/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Heikenashi200Response
 */
export interface Heikenashi200Response {
    /**
     * 
     * @type {Array<number>}
     * @memberof Heikenashi200Response
     */
    open?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Heikenashi200Response
     */
    high?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Heikenashi200Response
     */
    low?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Heikenashi200Response
     */
    close?: Array<number>;
}

/**
 * Check if a given object implements the Heikenashi200Response interface.
 */
export function instanceOfHeikenashi200Response(value: object): value is Heikenashi200Response {
    return true;
}

export function Heikenashi200ResponseFromJSON(json: any): Heikenashi200Response {
    return Heikenashi200ResponseFromJSONTyped(json, false);
}

export function Heikenashi200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Heikenashi200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'open': json['open'] == null ? undefined : json['open'],
        'high': json['high'] == null ? undefined : json['high'],
        'low': json['low'] == null ? undefined : json['low'],
        'close': json['close'] == null ? undefined : json['close'],
    };
}

export function Heikenashi200ResponseToJSON(json: any): Heikenashi200Response {
    return Heikenashi200ResponseToJSONTyped(json, false);
}

export function Heikenashi200ResponseToJSONTyped(value?: Heikenashi200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'open': value['open'],
        'high': value['high'],
        'low': value['low'],
        'close': value['close'],
    };
}

