/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * The trading pair symbol.
     * @type {string}
     * @memberof Metadata
     */
    symbol: string;
    /**
     * The timeframe used for the candles.
     * @type {string}
     * @memberof Metadata
     */
    timeframe: string;
    /**
     * ISO timestamp of the first available candle.
     * @type {Date}
     * @memberof Metadata
     */
    firstCandle: Date;
    /**
     * ISO timestamp of the last available candle.
     * @type {Date}
     * @memberof Metadata
     */
    lastCandle: Date;
    /**
     * Total number of available candles.
     * @type {number}
     * @memberof Metadata
     */
    totalCandles: number;
    /**
     * Completion percentage (0–100) as a string with two decimals.
     * @type {string}
     * @memberof Metadata
     */
    completionPercent: string;
    /**
     * Estimated date when full data collection will complete.
     * @type {Date}
     * @memberof Metadata
     */
    estimatedCompletionDate: Date;
}

/**
 * Check if a given object implements the Metadata interface.
 */
export function instanceOfMetadata(value: object): value is Metadata {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('timeframe' in value) || value['timeframe'] === undefined) return false;
    if (!('firstCandle' in value) || value['firstCandle'] === undefined) return false;
    if (!('lastCandle' in value) || value['lastCandle'] === undefined) return false;
    if (!('totalCandles' in value) || value['totalCandles'] === undefined) return false;
    if (!('completionPercent' in value) || value['completionPercent'] === undefined) return false;
    if (!('estimatedCompletionDate' in value) || value['estimatedCompletionDate'] === undefined) return false;
    return true;
}

export function MetadataFromJSON(json: any): Metadata {
    return MetadataFromJSONTyped(json, false);
}

export function MetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Metadata {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'timeframe': json['timeframe'],
        'firstCandle': (new Date(json['firstCandle'])),
        'lastCandle': (new Date(json['lastCandle'])),
        'totalCandles': json['totalCandles'],
        'completionPercent': json['completionPercent'],
        'estimatedCompletionDate': (new Date(json['estimatedCompletionDate'])),
    };
}

export function MetadataToJSON(json: any): Metadata {
    return MetadataToJSONTyped(json, false);
}

export function MetadataToJSONTyped(value?: Metadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
        'timeframe': value['timeframe'],
        'firstCandle': value['firstCandle'].toISOString(),
        'lastCandle': value['lastCandle'].toISOString(),
        'totalCandles': value['totalCandles'],
        'completionPercent': value['completionPercent'],
        'estimatedCompletionDate': value['estimatedCompletionDate'].toISOString(),
    };
}

