/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Pivot200ResponseInner
 */
export interface Pivot200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof Pivot200ResponseInner
     */
    p?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Pivot200ResponseInner
     */
    r1?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Pivot200ResponseInner
     */
    s1?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Pivot200ResponseInner
     */
    r2?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Pivot200ResponseInner
     */
    s2?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Pivot200ResponseInner
     */
    r3?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Pivot200ResponseInner
     */
    s3?: number | null;
}

/**
 * Check if a given object implements the Pivot200ResponseInner interface.
 */
export function instanceOfPivot200ResponseInner(value: object): value is Pivot200ResponseInner {
    return true;
}

export function Pivot200ResponseInnerFromJSON(json: any): Pivot200ResponseInner {
    return Pivot200ResponseInnerFromJSONTyped(json, false);
}

export function Pivot200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pivot200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'p': json['p'] == null ? undefined : json['p'],
        'r1': json['r1'] == null ? undefined : json['r1'],
        's1': json['s1'] == null ? undefined : json['s1'],
        'r2': json['r2'] == null ? undefined : json['r2'],
        's2': json['s2'] == null ? undefined : json['s2'],
        'r3': json['r3'] == null ? undefined : json['r3'],
        's3': json['s3'] == null ? undefined : json['s3'],
    };
}

export function Pivot200ResponseInnerToJSON(json: any): Pivot200ResponseInner {
    return Pivot200ResponseInnerToJSONTyped(json, false);
}

export function Pivot200ResponseInnerToJSONTyped(value?: Pivot200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'p': value['p'],
        'r1': value['r1'],
        's1': value['s1'],
        'r2': value['r2'],
        's2': value['s2'],
        'r3': value['r3'],
        's3': value['s3'],
    };
}

