/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StochRequestParams } from './StochRequestParams';
import {
    StochRequestParamsFromJSON,
    StochRequestParamsFromJSONTyped,
    StochRequestParamsToJSON,
    StochRequestParamsToJSONTyped,
} from './StochRequestParams';
import type { Candle } from './Candle';
import {
    CandleFromJSON,
    CandleFromJSONTyped,
    CandleToJSON,
    CandleToJSONTyped,
} from './Candle';

/**
 * 
 * @export
 * @interface StochRequest
 */
export interface StochRequest {
    /**
     * 
     * @type {Array<Candle>}
     * @memberof StochRequest
     */
    data: Array<Candle>;
    /**
     * 
     * @type {StochRequestParams}
     * @memberof StochRequest
     */
    params?: StochRequestParams;
}

/**
 * Check if a given object implements the StochRequest interface.
 */
export function instanceOfStochRequest(value: object): value is StochRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function StochRequestFromJSON(json: any): StochRequest {
    return StochRequestFromJSONTyped(json, false);
}

export function StochRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StochRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CandleFromJSON)),
        'params': json['params'] == null ? undefined : StochRequestParamsFromJSON(json['params']),
    };
}

export function StochRequestToJSON(json: any): StochRequest {
    return StochRequestToJSONTyped(json, false);
}

export function StochRequestToJSONTyped(value?: StochRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CandleToJSON)),
        'params': StochRequestParamsToJSON(value['params']),
    };
}

