/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Supertrend200ResponseInner
 */
export interface Supertrend200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof Supertrend200ResponseInner
     */
    value?: number;
    /**
     * 
     * @type {number}
     * @memberof Supertrend200ResponseInner
     */
    trend?: number;
}

/**
 * Check if a given object implements the Supertrend200ResponseInner interface.
 */
export function instanceOfSupertrend200ResponseInner(value: object): value is Supertrend200ResponseInner {
    return true;
}

export function Supertrend200ResponseInnerFromJSON(json: any): Supertrend200ResponseInner {
    return Supertrend200ResponseInnerFromJSONTyped(json, false);
}

export function Supertrend200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Supertrend200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'trend': json['trend'] == null ? undefined : json['trend'],
    };
}

export function Supertrend200ResponseInnerToJSON(json: any): Supertrend200ResponseInner {
    return Supertrend200ResponseInnerToJSONTyped(json, false);
}

export function Supertrend200ResponseInnerToJSONTyped(value?: Supertrend200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'trend': value['trend'],
    };
}

