/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.6
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Candle } from './Candle';
import {
    CandleFromJSON,
    CandleFromJSONTyped,
    CandleToJSON,
    CandleToJSONTyped,
} from './Candle';

/**
 * 
 * @export
 * @interface VwapRequest
 */
export interface VwapRequest {
    /**
     * 
     * @type {Array<Candle>}
     * @memberof VwapRequest
     */
    data: Array<Candle>;
}

/**
 * Check if a given object implements the VwapRequest interface.
 */
export function instanceOfVwapRequest(value: object): value is VwapRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function VwapRequestFromJSON(json: any): VwapRequest {
    return VwapRequestFromJSONTyped(json, false);
}

export function VwapRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VwapRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CandleFromJSON)),
    };
}

export function VwapRequestToJSON(json: any): VwapRequest {
    return VwapRequestToJSONTyped(json, false);
}

export function VwapRequestToJSONTyped(value?: VwapRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CandleToJSON)),
    };
}

