//
// BasicIndicatorsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class BasicIndicatorsAPI {

    /**
     Calculate Exponential Moving Average (EMA)
     
     - parameter emaRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func ema(emaRequest: EmaRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return emaWithRequestBuilder(emaRequest: emaRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Exponential Moving Average (EMA)
     - POST /api/indicators/ema
     - Returns the EMA of the close prices.
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter emaRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func emaWithRequestBuilder(emaRequest: EmaRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/ema"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: emaRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Relative Strength Index (RSI)
     
     - parameter emaRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func rsi(emaRequest: EmaRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return rsiWithRequestBuilder(emaRequest: emaRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Relative Strength Index (RSI)
     - POST /api/indicators/rsi
     - Returns the RSI of the close prices.
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter emaRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func rsiWithRequestBuilder(emaRequest: EmaRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/rsi"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: emaRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Simple Moving Average (SMA)
     
     - parameter smaRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func sma(smaRequest: SmaRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return smaWithRequestBuilder(smaRequest: smaRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Simple Moving Average (SMA)
     - POST /api/indicators/sma
     - Returns the SMA of the close prices.
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter smaRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func smaWithRequestBuilder(smaRequest: SmaRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/sma"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: smaRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
