//
// CalendarAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CalendarAPI {

    /**
     Get economic calendar within a selected period
     
     - parameter startDate: (query) Javascript style epoch time with milliseconds (i.e. 1762194992000). (optional)
     - parameter endDate: (query) Javascript style epoch time with milliseconds (i.e. 1762194992000). (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func calendar(startDate: Int64? = nil, endDate: Int64? = nil, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [CalendarEvent]?, _ error: Error?) -> Void)) -> RequestTask {
        return calendarWithRequestBuilder(startDate: startDate, endDate: endDate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get economic calendar within a selected period
     - GET /api/calendar
     - Fetch economic calendar for event based trading simulations. If no dates entered, data will be from -3 days from today to +3 days.
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter startDate: (query) Javascript style epoch time with milliseconds (i.e. 1762194992000). (optional)
     - parameter endDate: (query) Javascript style epoch time with milliseconds (i.e. 1762194992000). (optional)
     - returns: RequestBuilder<[CalendarEvent]> 
     */
    open class func calendarWithRequestBuilder(startDate: Int64? = nil, endDate: Int64? = nil) -> RequestBuilder<[CalendarEvent]> {
        let localVariablePath = "/api/calendar"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "startDate": (wrappedValue: startDate?.encodeToJSON(), isExplode: true),
            "endDate": (wrappedValue: endDate?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[CalendarEvent]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
