//
// IndicatorsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class IndicatorsAPI {

    /**
     Calculate Average Directional Index (ADX)
     
     - parameter adxRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adx(adxRequest: AdxRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Adx200ResponseInner]?, _ error: Error?) -> Void)) -> RequestTask {
        return adxWithRequestBuilder(adxRequest: adxRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Average Directional Index (ADX)
     - POST /api/indicators/adx
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter adxRequest: (body)  
     - returns: RequestBuilder<[Adx200ResponseInner]> 
     */
    open class func adxWithRequestBuilder(adxRequest: AdxRequest) -> RequestBuilder<[Adx200ResponseInner]> {
        let localVariablePath = "/api/indicators/adx"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: adxRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Adx200ResponseInner]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Average True Range (ATR)
     
     - parameter atrRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func atr(atrRequest: AtrRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return atrWithRequestBuilder(atrRequest: atrRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Average True Range (ATR)
     - POST /api/indicators/atr
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter atrRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func atrWithRequestBuilder(atrRequest: AtrRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/atr"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: atrRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Bollinger Bands
     
     - parameter bbandsRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func bbands(bbandsRequest: BbandsRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Bbands200ResponseInner]?, _ error: Error?) -> Void)) -> RequestTask {
        return bbandsWithRequestBuilder(bbandsRequest: bbandsRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Bollinger Bands
     - POST /api/indicators/bbands
     - Returns Upper, Middle, and Lower bands.
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter bbandsRequest: (body)  
     - returns: RequestBuilder<[Bbands200ResponseInner]> 
     */
    open class func bbandsWithRequestBuilder(bbandsRequest: BbandsRequest) -> RequestBuilder<[Bbands200ResponseInner]> {
        let localVariablePath = "/api/indicators/bbands"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: bbandsRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Bbands200ResponseInner]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Commodity Channel Index (CCI)
     
     - parameter cciRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func cci(cciRequest: CciRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return cciWithRequestBuilder(cciRequest: cciRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Commodity Channel Index (CCI)
     - POST /api/indicators/cci
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter cciRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func cciWithRequestBuilder(cciRequest: CciRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/cci"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: cciRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Exponential Moving Average (EMA)
     
     - parameter emaRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func ema(emaRequest: EmaRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return emaWithRequestBuilder(emaRequest: emaRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Exponential Moving Average (EMA)
     - POST /api/indicators/ema
     - Returns the EMA of the close prices.
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter emaRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func emaWithRequestBuilder(emaRequest: EmaRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/ema"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: emaRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Heiken Ashi
     
     - parameter heikenashiRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func heikenashi(heikenashiRequest: HeikenashiRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Candle]?, _ error: Error?) -> Void)) -> RequestTask {
        return heikenashiWithRequestBuilder(heikenashiRequest: heikenashiRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Heiken Ashi
     - POST /api/indicators/heikenashi
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter heikenashiRequest: (body)  
     - returns: RequestBuilder<[Candle]> 
     */
    open class func heikenashiWithRequestBuilder(heikenashiRequest: HeikenashiRequest) -> RequestBuilder<[Candle]> {
        let localVariablePath = "/api/indicators/heikenashi"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: heikenashiRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Candle]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Ichimoku Cloud
     
     - parameter ichimokuRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func ichimoku(ichimokuRequest: IchimokuRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Ichimoku200ResponseInner]?, _ error: Error?) -> Void)) -> RequestTask {
        return ichimokuWithRequestBuilder(ichimokuRequest: ichimokuRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Ichimoku Cloud
     - POST /api/indicators/ichimoku
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter ichimokuRequest: (body)  
     - returns: RequestBuilder<[Ichimoku200ResponseInner]> 
     */
    open class func ichimokuWithRequestBuilder(ichimokuRequest: IchimokuRequest) -> RequestBuilder<[Ichimoku200ResponseInner]> {
        let localVariablePath = "/api/indicators/ichimoku"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: ichimokuRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Ichimoku200ResponseInner]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Keltner Channels
     
     - parameter keltnerRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func keltner(keltnerRequest: KeltnerRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Bbands200ResponseInner]?, _ error: Error?) -> Void)) -> RequestTask {
        return keltnerWithRequestBuilder(keltnerRequest: keltnerRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Keltner Channels
     - POST /api/indicators/keltner
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter keltnerRequest: (body)  
     - returns: RequestBuilder<[Bbands200ResponseInner]> 
     */
    open class func keltnerWithRequestBuilder(keltnerRequest: KeltnerRequest) -> RequestBuilder<[Bbands200ResponseInner]> {
        let localVariablePath = "/api/indicators/keltner"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: keltnerRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Bbands200ResponseInner]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate MACD
     
     - parameter macdRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func macd(macdRequest: MacdRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Macd200ResponseInner]?, _ error: Error?) -> Void)) -> RequestTask {
        return macdWithRequestBuilder(macdRequest: macdRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate MACD
     - POST /api/indicators/macd
     - Returns MACD, Signal, and Histogram.
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter macdRequest: (body)  
     - returns: RequestBuilder<[Macd200ResponseInner]> 
     */
    open class func macdWithRequestBuilder(macdRequest: MacdRequest) -> RequestBuilder<[Macd200ResponseInner]> {
        let localVariablePath = "/api/indicators/macd"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: macdRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Macd200ResponseInner]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Pivot Points
     
     - parameter pivotRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func pivot(pivotRequest: PivotRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Pivot200ResponseInner]?, _ error: Error?) -> Void)) -> RequestTask {
        return pivotWithRequestBuilder(pivotRequest: pivotRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Pivot Points
     - POST /api/indicators/pivot
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter pivotRequest: (body)  
     - returns: RequestBuilder<[Pivot200ResponseInner]> 
     */
    open class func pivotWithRequestBuilder(pivotRequest: PivotRequest) -> RequestBuilder<[Pivot200ResponseInner]> {
        let localVariablePath = "/api/indicators/pivot"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: pivotRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Pivot200ResponseInner]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Parabolic SAR
     
     - parameter psarRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func psar(psarRequest: PsarRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return psarWithRequestBuilder(psarRequest: psarRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Parabolic SAR
     - POST /api/indicators/psar
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter psarRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func psarWithRequestBuilder(psarRequest: PsarRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/psar"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: psarRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Relative Strength Index (RSI)
     
     - parameter rsiRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func rsi(rsiRequest: RsiRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return rsiWithRequestBuilder(rsiRequest: rsiRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Relative Strength Index (RSI)
     - POST /api/indicators/rsi
     - Returns the RSI of the close prices.
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter rsiRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func rsiWithRequestBuilder(rsiRequest: RsiRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/rsi"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: rsiRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Simple Moving Average (SMA)
     
     - parameter smaRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func sma(smaRequest: SmaRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return smaWithRequestBuilder(smaRequest: smaRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Simple Moving Average (SMA)
     - POST /api/indicators/sma
     - Returns the SMA of the close prices.
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter smaRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func smaWithRequestBuilder(smaRequest: SmaRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/sma"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: smaRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Stochastic Oscillator
     
     - parameter stochRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func stoch(stochRequest: StochRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Stoch200ResponseInner]?, _ error: Error?) -> Void)) -> RequestTask {
        return stochWithRequestBuilder(stochRequest: stochRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Stochastic Oscillator
     - POST /api/indicators/stoch
     - Returns %K and %D lines.
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter stochRequest: (body)  
     - returns: RequestBuilder<[Stoch200ResponseInner]> 
     */
    open class func stochWithRequestBuilder(stochRequest: StochRequest) -> RequestBuilder<[Stoch200ResponseInner]> {
        let localVariablePath = "/api/indicators/stoch"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: stochRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Stoch200ResponseInner]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate SuperTrend
     
     - parameter supertrendRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func supertrend(supertrendRequest: SupertrendRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Supertrend200ResponseInner]?, _ error: Error?) -> Void)) -> RequestTask {
        return supertrendWithRequestBuilder(supertrendRequest: supertrendRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate SuperTrend
     - POST /api/indicators/supertrend
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter supertrendRequest: (body)  
     - returns: RequestBuilder<[Supertrend200ResponseInner]> 
     */
    open class func supertrendWithRequestBuilder(supertrendRequest: SupertrendRequest) -> RequestBuilder<[Supertrend200ResponseInner]> {
        let localVariablePath = "/api/indicators/supertrend"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: supertrendRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Supertrend200ResponseInner]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Volume MA
     
     - parameter volumemaRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func volumema(volumemaRequest: VolumemaRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return volumemaWithRequestBuilder(volumemaRequest: volumemaRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Volume MA
     - POST /api/indicators/volumema
     - Returns Simple Moving Average of Volume.
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter volumemaRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func volumemaWithRequestBuilder(volumemaRequest: VolumemaRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/volumema"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: volumemaRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate VWAP
     
     - parameter vwapRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func vwap(vwapRequest: VwapRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return vwapWithRequestBuilder(vwapRequest: vwapRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate VWAP
     - POST /api/indicators/vwap
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter vwapRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func vwapWithRequestBuilder(vwapRequest: VwapRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/vwap"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: vwapRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Williams %R
     
     - parameter williamsrRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func williamsr(williamsrRequest: WilliamsrRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return williamsrWithRequestBuilder(williamsrRequest: williamsrRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Williams %R
     - POST /api/indicators/williamsr
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter williamsrRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func williamsrWithRequestBuilder(williamsrRequest: WilliamsrRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/williamsr"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: williamsrRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate ZigZag Indicator
     
     - parameter zigzagRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func zigzag(zigzagRequest: ZigzagRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return zigzagWithRequestBuilder(zigzagRequest: zigzagRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate ZigZag Indicator
     - POST /api/indicators/zigzag
     - API Key:
       - type: apiKey X-TickCatcher-Key (HEADER)
       - name: directToken
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter zigzagRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func zigzagWithRequestBuilder(zigzagRequest: ZigzagRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/zigzag"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: zigzagRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
