//
// MegaIndicatorsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MegaIndicatorsAPI {

    /**
     Calculate Heiken Ashi
     
     - parameter heikenashiRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func heikenashi(heikenashiRequest: HeikenashiRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Candle]?, _ error: Error?) -> Void)) -> RequestTask {
        return heikenashiWithRequestBuilder(heikenashiRequest: heikenashiRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Heiken Ashi
     - POST /api/indicators/heikenashi
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter heikenashiRequest: (body)  
     - returns: RequestBuilder<[Candle]> 
     */
    open class func heikenashiWithRequestBuilder(heikenashiRequest: HeikenashiRequest) -> RequestBuilder<[Candle]> {
        let localVariablePath = "/api/indicators/heikenashi"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: heikenashiRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Candle]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Ichimoku Cloud
     
     - parameter ichimokuRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func ichimoku(ichimokuRequest: IchimokuRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Ichimoku200ResponseInner]?, _ error: Error?) -> Void)) -> RequestTask {
        return ichimokuWithRequestBuilder(ichimokuRequest: ichimokuRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Ichimoku Cloud
     - POST /api/indicators/ichimoku
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter ichimokuRequest: (body)  
     - returns: RequestBuilder<[Ichimoku200ResponseInner]> 
     */
    open class func ichimokuWithRequestBuilder(ichimokuRequest: IchimokuRequest) -> RequestBuilder<[Ichimoku200ResponseInner]> {
        let localVariablePath = "/api/indicators/ichimoku"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: ichimokuRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Ichimoku200ResponseInner]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate SuperTrend
     
     - parameter supertrendRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func supertrend(supertrendRequest: SupertrendRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Supertrend200ResponseInner]?, _ error: Error?) -> Void)) -> RequestTask {
        return supertrendWithRequestBuilder(supertrendRequest: supertrendRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate SuperTrend
     - POST /api/indicators/supertrend
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter supertrendRequest: (body)  
     - returns: RequestBuilder<[Supertrend200ResponseInner]> 
     */
    open class func supertrendWithRequestBuilder(supertrendRequest: SupertrendRequest) -> RequestBuilder<[Supertrend200ResponseInner]> {
        let localVariablePath = "/api/indicators/supertrend"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: supertrendRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Supertrend200ResponseInner]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Calculate Williams %R
     
     - parameter emaRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func williamsr(emaRequest: EmaRequest, apiResponseQueue: DispatchQueue = tickcatcherAPI.apiResponseQueue, completion: @escaping ((_ data: [Double]?, _ error: Error?) -> Void)) -> RequestTask {
        return williamsrWithRequestBuilder(emaRequest: emaRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Calculate Williams %R
     - POST /api/indicators/williamsr
     - API Key:
       - type: apiKey X-RapidAPI-Key (HEADER)
       - name: rapidapiKey
     - parameter emaRequest: (body)  
     - returns: RequestBuilder<[Double]> 
     */
    open class func williamsrWithRequestBuilder(emaRequest: EmaRequest) -> RequestBuilder<[Double]> {
        let localVariablePath = "/api/indicators/williamsr"
        let localVariableURLString = tickcatcherAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: emaRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Double]>.Type = tickcatcherAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
