/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: yagiz@iskirik.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bbands200ResponseInner {
    #[serde(rename = "upper", skip_serializing_if = "Option::is_none")]
    pub upper: Option<f64>,
    #[serde(rename = "middle", skip_serializing_if = "Option::is_none")]
    pub middle: Option<f64>,
    #[serde(rename = "lower", skip_serializing_if = "Option::is_none")]
    pub lower: Option<f64>,
}

impl Bbands200ResponseInner {
    pub fn new() -> Bbands200ResponseInner {
        Bbands200ResponseInner {
            upper: None,
            middle: None,
            lower: None,
        }
    }
}

