/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: yagiz@iskirik.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HeikenashiRequest {
    #[serde(rename = "data")]
    pub data: Vec<models::Candle>,
}

impl HeikenashiRequest {
    pub fn new(data: Vec<models::Candle>) -> HeikenashiRequest {
        HeikenashiRequest {
            data,
        }
    }
}

