/*
 * Tickcatcher API
 *
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.5
 * Contact: yagiz@iskirik.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pivot200ResponseInner {
    #[serde(rename = "p", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub p: Option<Option<f64>>,
    #[serde(rename = "r1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r1: Option<Option<f64>>,
    #[serde(rename = "s1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub s1: Option<Option<f64>>,
    #[serde(rename = "r2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r2: Option<Option<f64>>,
    #[serde(rename = "s2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub s2: Option<Option<f64>>,
    #[serde(rename = "r3", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r3: Option<Option<f64>>,
    #[serde(rename = "s3", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub s3: Option<Option<f64>>,
}

impl Pivot200ResponseInner {
    pub fn new() -> Pivot200ResponseInner {
        Pivot200ResponseInner {
            p: None,
            r1: None,
            s1: None,
            r2: None,
            s2: None,
            r3: None,
            s3: None,
        }
    }
}

