/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Metadata

class MetadataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Metadata
        //val modelInstance = Metadata()

        // to test the property `symbol` - The trading pair symbol.
        should("test symbol") {
            // uncomment below to test the property
            //modelInstance.symbol shouldBe ("TODO")
        }

        // to test the property `timeframe` - The timeframe used for the candles.
        should("test timeframe") {
            // uncomment below to test the property
            //modelInstance.timeframe shouldBe ("TODO")
        }

        // to test the property `firstCandle` - ISO timestamp of the first available candle.
        should("test firstCandle") {
            // uncomment below to test the property
            //modelInstance.firstCandle shouldBe ("TODO")
        }

        // to test the property `lastCandle` - ISO timestamp of the last available candle.
        should("test lastCandle") {
            // uncomment below to test the property
            //modelInstance.lastCandle shouldBe ("TODO")
        }

        // to test the property `totalCandles` - Total number of available candles.
        should("test totalCandles") {
            // uncomment below to test the property
            //modelInstance.totalCandles shouldBe ("TODO")
        }

        // to test the property `completionPercent` - Completion percentage (0–100) as a string with two decimals.
        should("test completionPercent") {
            // uncomment below to test the property
            //modelInstance.completionPercent shouldBe ("TODO")
        }

        // to test the property `estimatedCompletionDate` - Estimated date when full data collection will complete.
        should("test estimatedCompletionDate") {
            // uncomment below to test the property
            //modelInstance.estimatedCompletionDate shouldBe ("TODO")
        }

    }
}
