/*
Tickcatcher API

The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

API version: 1.1.0
Contact: yagiz@iskirik.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tickcatcher

import (
	"encoding/json"
)

// checks if the ApiIndicatorsMacdPostRequestParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiIndicatorsMacdPostRequestParams{}

// ApiIndicatorsMacdPostRequestParams struct for ApiIndicatorsMacdPostRequestParams
type ApiIndicatorsMacdPostRequestParams struct {
	FastPeriod *int32 `json:"fastPeriod,omitempty"`
	SlowPeriod *int32 `json:"slowPeriod,omitempty"`
	SignalPeriod *int32 `json:"signalPeriod,omitempty"`
}

// NewApiIndicatorsMacdPostRequestParams instantiates a new ApiIndicatorsMacdPostRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiIndicatorsMacdPostRequestParams() *ApiIndicatorsMacdPostRequestParams {
	this := ApiIndicatorsMacdPostRequestParams{}
	var fastPeriod int32 = 12
	this.FastPeriod = &fastPeriod
	var slowPeriod int32 = 26
	this.SlowPeriod = &slowPeriod
	var signalPeriod int32 = 9
	this.SignalPeriod = &signalPeriod
	return &this
}

// NewApiIndicatorsMacdPostRequestParamsWithDefaults instantiates a new ApiIndicatorsMacdPostRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiIndicatorsMacdPostRequestParamsWithDefaults() *ApiIndicatorsMacdPostRequestParams {
	this := ApiIndicatorsMacdPostRequestParams{}
	var fastPeriod int32 = 12
	this.FastPeriod = &fastPeriod
	var slowPeriod int32 = 26
	this.SlowPeriod = &slowPeriod
	var signalPeriod int32 = 9
	this.SignalPeriod = &signalPeriod
	return &this
}

// GetFastPeriod returns the FastPeriod field value if set, zero value otherwise.
func (o *ApiIndicatorsMacdPostRequestParams) GetFastPeriod() int32 {
	if o == nil || IsNil(o.FastPeriod) {
		var ret int32
		return ret
	}
	return *o.FastPeriod
}

// GetFastPeriodOk returns a tuple with the FastPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiIndicatorsMacdPostRequestParams) GetFastPeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.FastPeriod) {
		return nil, false
	}
	return o.FastPeriod, true
}

// HasFastPeriod returns a boolean if a field has been set.
func (o *ApiIndicatorsMacdPostRequestParams) HasFastPeriod() bool {
	if o != nil && !IsNil(o.FastPeriod) {
		return true
	}

	return false
}

// SetFastPeriod gets a reference to the given int32 and assigns it to the FastPeriod field.
func (o *ApiIndicatorsMacdPostRequestParams) SetFastPeriod(v int32) {
	o.FastPeriod = &v
}

// GetSlowPeriod returns the SlowPeriod field value if set, zero value otherwise.
func (o *ApiIndicatorsMacdPostRequestParams) GetSlowPeriod() int32 {
	if o == nil || IsNil(o.SlowPeriod) {
		var ret int32
		return ret
	}
	return *o.SlowPeriod
}

// GetSlowPeriodOk returns a tuple with the SlowPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiIndicatorsMacdPostRequestParams) GetSlowPeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.SlowPeriod) {
		return nil, false
	}
	return o.SlowPeriod, true
}

// HasSlowPeriod returns a boolean if a field has been set.
func (o *ApiIndicatorsMacdPostRequestParams) HasSlowPeriod() bool {
	if o != nil && !IsNil(o.SlowPeriod) {
		return true
	}

	return false
}

// SetSlowPeriod gets a reference to the given int32 and assigns it to the SlowPeriod field.
func (o *ApiIndicatorsMacdPostRequestParams) SetSlowPeriod(v int32) {
	o.SlowPeriod = &v
}

// GetSignalPeriod returns the SignalPeriod field value if set, zero value otherwise.
func (o *ApiIndicatorsMacdPostRequestParams) GetSignalPeriod() int32 {
	if o == nil || IsNil(o.SignalPeriod) {
		var ret int32
		return ret
	}
	return *o.SignalPeriod
}

// GetSignalPeriodOk returns a tuple with the SignalPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiIndicatorsMacdPostRequestParams) GetSignalPeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.SignalPeriod) {
		return nil, false
	}
	return o.SignalPeriod, true
}

// HasSignalPeriod returns a boolean if a field has been set.
func (o *ApiIndicatorsMacdPostRequestParams) HasSignalPeriod() bool {
	if o != nil && !IsNil(o.SignalPeriod) {
		return true
	}

	return false
}

// SetSignalPeriod gets a reference to the given int32 and assigns it to the SignalPeriod field.
func (o *ApiIndicatorsMacdPostRequestParams) SetSignalPeriod(v int32) {
	o.SignalPeriod = &v
}

func (o ApiIndicatorsMacdPostRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiIndicatorsMacdPostRequestParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FastPeriod) {
		toSerialize["fastPeriod"] = o.FastPeriod
	}
	if !IsNil(o.SlowPeriod) {
		toSerialize["slowPeriod"] = o.SlowPeriod
	}
	if !IsNil(o.SignalPeriod) {
		toSerialize["signalPeriod"] = o.SignalPeriod
	}
	return toSerialize, nil
}

type NullableApiIndicatorsMacdPostRequestParams struct {
	value *ApiIndicatorsMacdPostRequestParams
	isSet bool
}

func (v NullableApiIndicatorsMacdPostRequestParams) Get() *ApiIndicatorsMacdPostRequestParams {
	return v.value
}

func (v *NullableApiIndicatorsMacdPostRequestParams) Set(val *ApiIndicatorsMacdPostRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableApiIndicatorsMacdPostRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableApiIndicatorsMacdPostRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiIndicatorsMacdPostRequestParams(val *ApiIndicatorsMacdPostRequestParams) *NullableApiIndicatorsMacdPostRequestParams {
	return &NullableApiIndicatorsMacdPostRequestParams{value: val, isSet: true}
}

func (v NullableApiIndicatorsMacdPostRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiIndicatorsMacdPostRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


