/*
Tickcatcher API

The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

API version: 1.1.0
Contact: yagiz@iskirik.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tickcatcher

import (
	"encoding/json"
)

// checks if the ApiIndicatorsStochPostRequestParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiIndicatorsStochPostRequestParams{}

// ApiIndicatorsStochPostRequestParams struct for ApiIndicatorsStochPostRequestParams
type ApiIndicatorsStochPostRequestParams struct {
	Period *int32 `json:"period,omitempty"`
	SignalPeriod *int32 `json:"signalPeriod,omitempty"`
}

// NewApiIndicatorsStochPostRequestParams instantiates a new ApiIndicatorsStochPostRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiIndicatorsStochPostRequestParams() *ApiIndicatorsStochPostRequestParams {
	this := ApiIndicatorsStochPostRequestParams{}
	var period int32 = 14
	this.Period = &period
	var signalPeriod int32 = 3
	this.SignalPeriod = &signalPeriod
	return &this
}

// NewApiIndicatorsStochPostRequestParamsWithDefaults instantiates a new ApiIndicatorsStochPostRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiIndicatorsStochPostRequestParamsWithDefaults() *ApiIndicatorsStochPostRequestParams {
	this := ApiIndicatorsStochPostRequestParams{}
	var period int32 = 14
	this.Period = &period
	var signalPeriod int32 = 3
	this.SignalPeriod = &signalPeriod
	return &this
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *ApiIndicatorsStochPostRequestParams) GetPeriod() int32 {
	if o == nil || IsNil(o.Period) {
		var ret int32
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiIndicatorsStochPostRequestParams) GetPeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *ApiIndicatorsStochPostRequestParams) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given int32 and assigns it to the Period field.
func (o *ApiIndicatorsStochPostRequestParams) SetPeriod(v int32) {
	o.Period = &v
}

// GetSignalPeriod returns the SignalPeriod field value if set, zero value otherwise.
func (o *ApiIndicatorsStochPostRequestParams) GetSignalPeriod() int32 {
	if o == nil || IsNil(o.SignalPeriod) {
		var ret int32
		return ret
	}
	return *o.SignalPeriod
}

// GetSignalPeriodOk returns a tuple with the SignalPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiIndicatorsStochPostRequestParams) GetSignalPeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.SignalPeriod) {
		return nil, false
	}
	return o.SignalPeriod, true
}

// HasSignalPeriod returns a boolean if a field has been set.
func (o *ApiIndicatorsStochPostRequestParams) HasSignalPeriod() bool {
	if o != nil && !IsNil(o.SignalPeriod) {
		return true
	}

	return false
}

// SetSignalPeriod gets a reference to the given int32 and assigns it to the SignalPeriod field.
func (o *ApiIndicatorsStochPostRequestParams) SetSignalPeriod(v int32) {
	o.SignalPeriod = &v
}

func (o ApiIndicatorsStochPostRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiIndicatorsStochPostRequestParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.SignalPeriod) {
		toSerialize["signalPeriod"] = o.SignalPeriod
	}
	return toSerialize, nil
}

type NullableApiIndicatorsStochPostRequestParams struct {
	value *ApiIndicatorsStochPostRequestParams
	isSet bool
}

func (v NullableApiIndicatorsStochPostRequestParams) Get() *ApiIndicatorsStochPostRequestParams {
	return v.value
}

func (v *NullableApiIndicatorsStochPostRequestParams) Set(val *ApiIndicatorsStochPostRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableApiIndicatorsStochPostRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableApiIndicatorsStochPostRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiIndicatorsStochPostRequestParams(val *ApiIndicatorsStochPostRequestParams) *NullableApiIndicatorsStochPostRequestParams {
	return &NullableApiIndicatorsStochPostRequestParams{value: val, isSet: true}
}

func (v NullableApiIndicatorsStochPostRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiIndicatorsStochPostRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


