/*
Tickcatcher API

The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

API version: 1.1.5
Contact: yagiz@iskirik.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tickcatcher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VolumemaRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VolumemaRequest{}

// VolumemaRequest struct for VolumemaRequest
type VolumemaRequest struct {
	Data []Candle `json:"data"`
	Params *EmaRequestParams `json:"params,omitempty"`
}

type _VolumemaRequest VolumemaRequest

// NewVolumemaRequest instantiates a new VolumemaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVolumemaRequest(data []Candle) *VolumemaRequest {
	this := VolumemaRequest{}
	this.Data = data
	return &this
}

// NewVolumemaRequestWithDefaults instantiates a new VolumemaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVolumemaRequestWithDefaults() *VolumemaRequest {
	this := VolumemaRequest{}
	return &this
}

// GetData returns the Data field value
func (o *VolumemaRequest) GetData() []Candle {
	if o == nil {
		var ret []Candle
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VolumemaRequest) GetDataOk() ([]Candle, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *VolumemaRequest) SetData(v []Candle) {
	o.Data = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *VolumemaRequest) GetParams() EmaRequestParams {
	if o == nil || IsNil(o.Params) {
		var ret EmaRequestParams
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumemaRequest) GetParamsOk() (*EmaRequestParams, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *VolumemaRequest) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given EmaRequestParams and assigns it to the Params field.
func (o *VolumemaRequest) SetParams(v EmaRequestParams) {
	o.Params = &v
}

func (o VolumemaRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VolumemaRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	return toSerialize, nil
}

func (o *VolumemaRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVolumemaRequest := _VolumemaRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVolumemaRequest)

	if err != nil {
		return err
	}

	*o = VolumemaRequest(varVolumemaRequest)

	return err
}

type NullableVolumemaRequest struct {
	value *VolumemaRequest
	isSet bool
}

func (v NullableVolumemaRequest) Get() *VolumemaRequest {
	return v.value
}

func (v *NullableVolumemaRequest) Set(val *VolumemaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumemaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumemaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumemaRequest(val *VolumemaRequest) *NullableVolumemaRequest {
	return &NullableVolumemaRequest{value: val, isSet: true}
}

func (v NullableVolumemaRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumemaRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


