/*
Tickcatcher API

The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key or TickCatcher Direct Key. 

API version: 1.1.7
Contact: yagiz@iskirik.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tickcatcher

import (
	"encoding/json"
)

// checks if the Pivot200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Pivot200ResponseInner{}

// Pivot200ResponseInner struct for Pivot200ResponseInner
type Pivot200ResponseInner struct {
	P NullableFloat32 `json:"p,omitempty"`
	R1 NullableFloat32 `json:"r1,omitempty"`
	S1 NullableFloat32 `json:"s1,omitempty"`
	R2 NullableFloat32 `json:"r2,omitempty"`
	S2 NullableFloat32 `json:"s2,omitempty"`
	R3 NullableFloat32 `json:"r3,omitempty"`
	S3 NullableFloat32 `json:"s3,omitempty"`
}

// NewPivot200ResponseInner instantiates a new Pivot200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPivot200ResponseInner() *Pivot200ResponseInner {
	this := Pivot200ResponseInner{}
	return &this
}

// NewPivot200ResponseInnerWithDefaults instantiates a new Pivot200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPivot200ResponseInnerWithDefaults() *Pivot200ResponseInner {
	this := Pivot200ResponseInner{}
	return &this
}

// GetP returns the P field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Pivot200ResponseInner) GetP() float32 {
	if o == nil || IsNil(o.P.Get()) {
		var ret float32
		return ret
	}
	return *o.P.Get()
}

// GetPOk returns a tuple with the P field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Pivot200ResponseInner) GetPOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.P.Get(), o.P.IsSet()
}

// HasP returns a boolean if a field has been set.
func (o *Pivot200ResponseInner) HasP() bool {
	if o != nil && o.P.IsSet() {
		return true
	}

	return false
}

// SetP gets a reference to the given NullableFloat32 and assigns it to the P field.
func (o *Pivot200ResponseInner) SetP(v float32) {
	o.P.Set(&v)
}
// SetPNil sets the value for P to be an explicit nil
func (o *Pivot200ResponseInner) SetPNil() {
	o.P.Set(nil)
}

// UnsetP ensures that no value is present for P, not even an explicit nil
func (o *Pivot200ResponseInner) UnsetP() {
	o.P.Unset()
}

// GetR1 returns the R1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Pivot200ResponseInner) GetR1() float32 {
	if o == nil || IsNil(o.R1.Get()) {
		var ret float32
		return ret
	}
	return *o.R1.Get()
}

// GetR1Ok returns a tuple with the R1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Pivot200ResponseInner) GetR1Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.R1.Get(), o.R1.IsSet()
}

// HasR1 returns a boolean if a field has been set.
func (o *Pivot200ResponseInner) HasR1() bool {
	if o != nil && o.R1.IsSet() {
		return true
	}

	return false
}

// SetR1 gets a reference to the given NullableFloat32 and assigns it to the R1 field.
func (o *Pivot200ResponseInner) SetR1(v float32) {
	o.R1.Set(&v)
}
// SetR1Nil sets the value for R1 to be an explicit nil
func (o *Pivot200ResponseInner) SetR1Nil() {
	o.R1.Set(nil)
}

// UnsetR1 ensures that no value is present for R1, not even an explicit nil
func (o *Pivot200ResponseInner) UnsetR1() {
	o.R1.Unset()
}

// GetS1 returns the S1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Pivot200ResponseInner) GetS1() float32 {
	if o == nil || IsNil(o.S1.Get()) {
		var ret float32
		return ret
	}
	return *o.S1.Get()
}

// GetS1Ok returns a tuple with the S1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Pivot200ResponseInner) GetS1Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.S1.Get(), o.S1.IsSet()
}

// HasS1 returns a boolean if a field has been set.
func (o *Pivot200ResponseInner) HasS1() bool {
	if o != nil && o.S1.IsSet() {
		return true
	}

	return false
}

// SetS1 gets a reference to the given NullableFloat32 and assigns it to the S1 field.
func (o *Pivot200ResponseInner) SetS1(v float32) {
	o.S1.Set(&v)
}
// SetS1Nil sets the value for S1 to be an explicit nil
func (o *Pivot200ResponseInner) SetS1Nil() {
	o.S1.Set(nil)
}

// UnsetS1 ensures that no value is present for S1, not even an explicit nil
func (o *Pivot200ResponseInner) UnsetS1() {
	o.S1.Unset()
}

// GetR2 returns the R2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Pivot200ResponseInner) GetR2() float32 {
	if o == nil || IsNil(o.R2.Get()) {
		var ret float32
		return ret
	}
	return *o.R2.Get()
}

// GetR2Ok returns a tuple with the R2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Pivot200ResponseInner) GetR2Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.R2.Get(), o.R2.IsSet()
}

// HasR2 returns a boolean if a field has been set.
func (o *Pivot200ResponseInner) HasR2() bool {
	if o != nil && o.R2.IsSet() {
		return true
	}

	return false
}

// SetR2 gets a reference to the given NullableFloat32 and assigns it to the R2 field.
func (o *Pivot200ResponseInner) SetR2(v float32) {
	o.R2.Set(&v)
}
// SetR2Nil sets the value for R2 to be an explicit nil
func (o *Pivot200ResponseInner) SetR2Nil() {
	o.R2.Set(nil)
}

// UnsetR2 ensures that no value is present for R2, not even an explicit nil
func (o *Pivot200ResponseInner) UnsetR2() {
	o.R2.Unset()
}

// GetS2 returns the S2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Pivot200ResponseInner) GetS2() float32 {
	if o == nil || IsNil(o.S2.Get()) {
		var ret float32
		return ret
	}
	return *o.S2.Get()
}

// GetS2Ok returns a tuple with the S2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Pivot200ResponseInner) GetS2Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.S2.Get(), o.S2.IsSet()
}

// HasS2 returns a boolean if a field has been set.
func (o *Pivot200ResponseInner) HasS2() bool {
	if o != nil && o.S2.IsSet() {
		return true
	}

	return false
}

// SetS2 gets a reference to the given NullableFloat32 and assigns it to the S2 field.
func (o *Pivot200ResponseInner) SetS2(v float32) {
	o.S2.Set(&v)
}
// SetS2Nil sets the value for S2 to be an explicit nil
func (o *Pivot200ResponseInner) SetS2Nil() {
	o.S2.Set(nil)
}

// UnsetS2 ensures that no value is present for S2, not even an explicit nil
func (o *Pivot200ResponseInner) UnsetS2() {
	o.S2.Unset()
}

// GetR3 returns the R3 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Pivot200ResponseInner) GetR3() float32 {
	if o == nil || IsNil(o.R3.Get()) {
		var ret float32
		return ret
	}
	return *o.R3.Get()
}

// GetR3Ok returns a tuple with the R3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Pivot200ResponseInner) GetR3Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.R3.Get(), o.R3.IsSet()
}

// HasR3 returns a boolean if a field has been set.
func (o *Pivot200ResponseInner) HasR3() bool {
	if o != nil && o.R3.IsSet() {
		return true
	}

	return false
}

// SetR3 gets a reference to the given NullableFloat32 and assigns it to the R3 field.
func (o *Pivot200ResponseInner) SetR3(v float32) {
	o.R3.Set(&v)
}
// SetR3Nil sets the value for R3 to be an explicit nil
func (o *Pivot200ResponseInner) SetR3Nil() {
	o.R3.Set(nil)
}

// UnsetR3 ensures that no value is present for R3, not even an explicit nil
func (o *Pivot200ResponseInner) UnsetR3() {
	o.R3.Unset()
}

// GetS3 returns the S3 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Pivot200ResponseInner) GetS3() float32 {
	if o == nil || IsNil(o.S3.Get()) {
		var ret float32
		return ret
	}
	return *o.S3.Get()
}

// GetS3Ok returns a tuple with the S3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Pivot200ResponseInner) GetS3Ok() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.S3.Get(), o.S3.IsSet()
}

// HasS3 returns a boolean if a field has been set.
func (o *Pivot200ResponseInner) HasS3() bool {
	if o != nil && o.S3.IsSet() {
		return true
	}

	return false
}

// SetS3 gets a reference to the given NullableFloat32 and assigns it to the S3 field.
func (o *Pivot200ResponseInner) SetS3(v float32) {
	o.S3.Set(&v)
}
// SetS3Nil sets the value for S3 to be an explicit nil
func (o *Pivot200ResponseInner) SetS3Nil() {
	o.S3.Set(nil)
}

// UnsetS3 ensures that no value is present for S3, not even an explicit nil
func (o *Pivot200ResponseInner) UnsetS3() {
	o.S3.Unset()
}

func (o Pivot200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Pivot200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.P.IsSet() {
		toSerialize["p"] = o.P.Get()
	}
	if o.R1.IsSet() {
		toSerialize["r1"] = o.R1.Get()
	}
	if o.S1.IsSet() {
		toSerialize["s1"] = o.S1.Get()
	}
	if o.R2.IsSet() {
		toSerialize["r2"] = o.R2.Get()
	}
	if o.S2.IsSet() {
		toSerialize["s2"] = o.S2.Get()
	}
	if o.R3.IsSet() {
		toSerialize["r3"] = o.R3.Get()
	}
	if o.S3.IsSet() {
		toSerialize["s3"] = o.S3.Get()
	}
	return toSerialize, nil
}

type NullablePivot200ResponseInner struct {
	value *Pivot200ResponseInner
	isSet bool
}

func (v NullablePivot200ResponseInner) Get() *Pivot200ResponseInner {
	return v.value
}

func (v *NullablePivot200ResponseInner) Set(val *Pivot200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePivot200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePivot200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePivot200ResponseInner(val *Pivot200ResponseInner) *NullablePivot200ResponseInner {
	return &NullablePivot200ResponseInner{value: val, isSet: true}
}

func (v NullablePivot200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePivot200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


