/*
Tickcatcher API

The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

API version: 1.1.0
Contact: yagiz@iskirik.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tickcatcher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiIndicatorsMacdPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiIndicatorsMacdPostRequest{}

// ApiIndicatorsMacdPostRequest struct for ApiIndicatorsMacdPostRequest
type ApiIndicatorsMacdPostRequest struct {
	Data CandleData `json:"data"`
	Params *ApiIndicatorsMacdPostRequestParams `json:"params,omitempty"`
}

type _ApiIndicatorsMacdPostRequest ApiIndicatorsMacdPostRequest

// NewApiIndicatorsMacdPostRequest instantiates a new ApiIndicatorsMacdPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiIndicatorsMacdPostRequest(data CandleData) *ApiIndicatorsMacdPostRequest {
	this := ApiIndicatorsMacdPostRequest{}
	this.Data = data
	return &this
}

// NewApiIndicatorsMacdPostRequestWithDefaults instantiates a new ApiIndicatorsMacdPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiIndicatorsMacdPostRequestWithDefaults() *ApiIndicatorsMacdPostRequest {
	this := ApiIndicatorsMacdPostRequest{}
	return &this
}

// GetData returns the Data field value
func (o *ApiIndicatorsMacdPostRequest) GetData() CandleData {
	if o == nil {
		var ret CandleData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApiIndicatorsMacdPostRequest) GetDataOk() (*CandleData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ApiIndicatorsMacdPostRequest) SetData(v CandleData) {
	o.Data = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *ApiIndicatorsMacdPostRequest) GetParams() ApiIndicatorsMacdPostRequestParams {
	if o == nil || IsNil(o.Params) {
		var ret ApiIndicatorsMacdPostRequestParams
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiIndicatorsMacdPostRequest) GetParamsOk() (*ApiIndicatorsMacdPostRequestParams, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *ApiIndicatorsMacdPostRequest) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given ApiIndicatorsMacdPostRequestParams and assigns it to the Params field.
func (o *ApiIndicatorsMacdPostRequest) SetParams(v ApiIndicatorsMacdPostRequestParams) {
	o.Params = &v
}

func (o ApiIndicatorsMacdPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiIndicatorsMacdPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	return toSerialize, nil
}

func (o *ApiIndicatorsMacdPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiIndicatorsMacdPostRequest := _ApiIndicatorsMacdPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiIndicatorsMacdPostRequest)

	if err != nil {
		return err
	}

	*o = ApiIndicatorsMacdPostRequest(varApiIndicatorsMacdPostRequest)

	return err
}

type NullableApiIndicatorsMacdPostRequest struct {
	value *ApiIndicatorsMacdPostRequest
	isSet bool
}

func (v NullableApiIndicatorsMacdPostRequest) Get() *ApiIndicatorsMacdPostRequest {
	return v.value
}

func (v *NullableApiIndicatorsMacdPostRequest) Set(val *ApiIndicatorsMacdPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiIndicatorsMacdPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiIndicatorsMacdPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiIndicatorsMacdPostRequest(val *ApiIndicatorsMacdPostRequest) *NullableApiIndicatorsMacdPostRequest {
	return &NullableApiIndicatorsMacdPostRequest{value: val, isSet: true}
}

func (v NullableApiIndicatorsMacdPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiIndicatorsMacdPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


