/*
Tickcatcher API

The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 

API version: 1.1.5
Contact: yagiz@iskirik.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tickcatcher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VwapRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VwapRequest{}

// VwapRequest struct for VwapRequest
type VwapRequest struct {
	Data []Candle `json:"data"`
}

type _VwapRequest VwapRequest

// NewVwapRequest instantiates a new VwapRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVwapRequest(data []Candle) *VwapRequest {
	this := VwapRequest{}
	this.Data = data
	return &this
}

// NewVwapRequestWithDefaults instantiates a new VwapRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVwapRequestWithDefaults() *VwapRequest {
	this := VwapRequest{}
	return &this
}

// GetData returns the Data field value
func (o *VwapRequest) GetData() []Candle {
	if o == nil {
		var ret []Candle
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VwapRequest) GetDataOk() ([]Candle, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *VwapRequest) SetData(v []Candle) {
	o.Data = v
}

func (o VwapRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VwapRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *VwapRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVwapRequest := _VwapRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVwapRequest)

	if err != nil {
		return err
	}

	*o = VwapRequest(varVwapRequest)

	return err
}

type NullableVwapRequest struct {
	value *VwapRequest
	isSet bool
}

func (v NullableVwapRequest) Get() *VwapRequest {
	return v.value
}

func (v *NullableVwapRequest) Set(val *VwapRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVwapRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVwapRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVwapRequest(val *VwapRequest) *NullableVwapRequest {
	return &NullableVwapRequest{value: val, isSet: true}
}

func (v NullableVwapRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVwapRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


