//
// Bbands200ResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Bbands200ResponseInner: Codable, JSONEncodable, Hashable {

    public var upper: Double?
    public var middle: Double?
    public var lower: Double?

    public init(upper: Double? = nil, middle: Double? = nil, lower: Double? = nil) {
        self.upper = upper
        self.middle = middle
        self.lower = lower
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case upper
        case middle
        case lower
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(upper, forKey: .upper)
        try container.encodeIfPresent(middle, forKey: .middle)
        try container.encodeIfPresent(lower, forKey: .lower)
    }
}

