/* tslint:disable */
/* eslint-disable */
/**
 * Tickcatcher API
 * The Tickcatcher API provides access to cryptocurrency market data including candlesticks, symbols, and indicators. All requests require authentication using your RapidAPI key. 
 *
 * The version of the OpenAPI document: 1.1.5
 * Contact: yagiz@iskirik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Info,
  Metadata,
  SearchResult,
} from '../models/index';
import {
    InfoFromJSON,
    InfoToJSON,
    MetadataFromJSON,
    MetadataToJSON,
    SearchResultFromJSON,
    SearchResultToJSON,
} from '../models/index';

export interface MetadataRequest {
    symbol: string;
    timeframe: MetadataTimeframeEnum;
}

export interface SearchRequest {
    query: string;
}

/**
 * 
 */
export class GeneralApi extends runtime.BaseAPI {

    /**
     * Get your current RapidAPI package, which coins you can use, maximum candles that you can request, etc.
     * Get your package information as well as your limitations
     */
    async infoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Info>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-RapidAPI-Key"] = await this.configuration.apiKey("X-RapidAPI-Key"); // rapidapiKey authentication
        }


        let urlPath = `/api/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InfoFromJSON(jsonValue));
    }

    /**
     * Get your current RapidAPI package, which coins you can use, maximum candles that you can request, etc.
     * Get your package information as well as your limitations
     */
    async info(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Info> {
        const response = await this.infoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve metadata for a specific symbol and timeframe.
     * Get metadata of selected timeframe/symbol pair
     */
    async metadataRaw(requestParameters: MetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Metadata>> {
        if (requestParameters['symbol'] == null) {
            throw new runtime.RequiredError(
                'symbol',
                'Required parameter "symbol" was null or undefined when calling metadata().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling metadata().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['symbol'] != null) {
            queryParameters['symbol'] = requestParameters['symbol'];
        }

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-RapidAPI-Key"] = await this.configuration.apiKey("X-RapidAPI-Key"); // rapidapiKey authentication
        }


        let urlPath = `/api/metadata`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataFromJSON(jsonValue));
    }

    /**
     * Retrieve metadata for a specific symbol and timeframe.
     * Get metadata of selected timeframe/symbol pair
     */
    async metadata(requestParameters: MetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Metadata> {
        const response = await this.metadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * If your queries don\'t work correctly, you can search the database with the coin name to get the correct symbol(s).
     * Search through the list of symbols to use correct one in the query
     */
    async searchRaw(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchResult>>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-RapidAPI-Key"] = await this.configuration.apiKey("X-RapidAPI-Key"); // rapidapiKey authentication
        }


        let urlPath = `/api/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchResultFromJSON));
    }

    /**
     * If your queries don\'t work correctly, you can search the database with the coin name to get the correct symbol(s).
     * Search through the list of symbols to use correct one in the query
     */
    async search(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchResult>> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const MetadataTimeframeEnum = {
    _1m: '1m',
    _5m: '5m',
    _15m: '15m',
    _1h: '1h',
    _4h: '4h'
} as const;
export type MetadataTimeframeEnum = typeof MetadataTimeframeEnum[keyof typeof MetadataTimeframeEnum];
